// -----------------------------------------------------------------------------
// ncs.snac_24kh.vq  —  generated by Max External Template Generator
// -----------------------------------------------------------------------------

#ifdef _WIN32
#include <windows.h>
#endif

#include "c74_min.h"
#include "ext.h"
#include "../include/tsqueue.h"

#include "../include/shared_external_helpers.h"
#include "../include/onnx_helpers.h"
#include <algorithm>
#include <atomic>
#include <chrono>
#include <cmath>
#include <memory>
#include <mutex>
#include <string>
#include <thread>
#include <utility>
#include <vector>

using namespace c74::min;

// SNAC 24kHz quantizer: 3 codebook levels, vq_strides=[4,2,1] (coarsest
// first). quantize_encodings.onnx has 1 input ("z") and 3 outputs
// (codes_0/1/2), each already at its own native temporal resolution
// (T/4, T/2, T) -- each level gets its own outlet, so no zero-order-hold
// expansion/interleaving is needed here.
static constexpr int kNumLevels = 3;

class NcsSnac_24khVq : public object<NcsSnac_24khVq>
{
public:
    MIN_DESCRIPTION     {"SNAC 24kHz residual vector quantizer: embeddings -> per-level codes."};
    MIN_TAGS            {"snac, onnx"};
    MIN_AUTHOR          {"Behzad Haki"};
    inlet<> control_in{ this, "(list/load) embeddings from ncs.snac_24kh.encode, or model path" };
    outlet<> level0_out{ this, "(list) codebook level 0 codes (coarsest, stride 4)" };
    outlet<> level1_out{ this, "(list) codebook level 1 codes (stride 2)" };
    outlet<> level2_out{ this, "(list) codebook level 2 codes (finest, stride 1)" };

    // =====================================================================
    // CONSTRUCTOR / DESTRUCTOR
    // =====================================================================
    NcsSnac_24khVq()
        : output_timer_{this, MIN_FUNCTION { flush_output(); output_timer_.delay(10); return {}; }}
    {
        start_worker();
        start_output_timer();
        // Auto-load the model shipped alongside this external. `load
        // <path>` still works afterwards to point at a different model.
        load_queue_.enqueue(BundleResourceLoader::get_resource_path(
            "models/snac_onnx_exports/24khz/quantize_encodings.onnx"));
    }

    ~NcsSnac_24khVq() {
        stop_worker();
        stop_output_timer();
    }

    // Errors go through log_queue_ (not error() inline) -- this can fire
    // very early during patch load, and calling error() synchronously at
    // that point has crashed Max's console/UI; deferring it to the timer
    // callback avoids that.
    message<> list_msg{this, "list", "Embeddings to quantize",
        MIN_FUNCTION {
            try {
                std::vector<float> emb(args.size());
                for (size_t i = 0; i < args.size(); ++i)
                    emb[i] = (float)args[i];
                input_queue_.enqueue(std::move(emb));
            } catch (const std::exception& ex) {
                log_queue_.enqueue({true, "ncs.snac_24kh.vq: list handling failed — " + std::string(ex.what())});
            }
            return {};
        }};

    message<> load{this, "load", "Load an ONNX model (.onnx)",
        MIN_FUNCTION {
            if (args.size() < 1) {
                log_queue_.enqueue({true, "ncs.snac_24kh.vq: load requires a file path"});
                return {};
            }
            load_queue_.enqueue((std::string)args[0]);
            return {};
        }};

// =============================================================================
// PRIVATE
// =============================================================================
private:
    std::thread worker_thread_;
    std::atomic<bool> worker_running_{false};
    std::atomic<bool> stop_{false};

    tsqueue<std::vector<float>> input_queue_;
    tsqueue<std::vector<std::vector<int>>> output_queue_;
    tsqueue<std::string> load_queue_;
    tsqueue<std::pair<bool,std::string>> log_queue_;

    timer<> output_timer_;

    bool model_loaded_{false};
    std::unique_ptr<Ort::Session> session_;
    Ort::SessionOptions session_options_;
    Ort::AllocatorWithDefaultOptions allocator_;
    std::string input_name_;
    std::vector<int64_t> input_dims_;
    std::vector<std::string> output_names_;

    void start_worker() {
        if (worker_running_.exchange(true)) return;
        stop_ = false;
        worker_thread_ = std::thread([this] { worker_loop(); });
    }

    void stop_worker() {
        stop_ = true;
        input_queue_.shutdown();
        load_queue_.shutdown();
        if (worker_thread_.joinable()) {
            if (worker_thread_.get_id() != std::this_thread::get_id())
                worker_thread_.join();
            else
                worker_thread_.detach();
        }
        worker_running_ = false;
    }

    void worker_loop() {
        while (!stop_) {
            std::string path;
            if (load_queue_.try_dequeue(path))
                load_model(path);
            std::vector<float> input;
            if (!input_queue_.wait_dequeue(input, 100))
                continue;
            std::vector<float> temp;
            while (input_queue_.try_dequeue(temp))
                input = std::move(temp);
            process(input);
        }
    }

    void process(const std::vector<float>& msg) {
        if (!model_loaded_) {
            log_queue_.enqueue({true, "ncs.snac_24kh.vq: no model loaded"});
            return;
        }
        auto result = run_onnx(msg);
        if (result.empty()) {
            log_queue_.enqueue({true, "ncs.snac_24kh.vq: inference failed"});
            return;
        }
        output_queue_.enqueue(std::move(result));
    }

    // Outlets fire right-to-left (level2 first, level0 last) -- the
    // standard Max convention, and lets a downstream ncs.snac_24kh.embedcodes
    // treat its leftmost (level0) inlet as the hot/triggering one once its
    // cold level1/level2 inlets have already been updated.
    // Every crash seen so far traced back to a call to error() -- post()
    // has been reliable throughout. Route everything through post() with
    // an "ERROR:" prefix instead, to avoid whatever error() is doing
    // (likely highlighting the object in the patcher) that's unsafe here.
    void flush_output() {
        std::pair<bool,std::string> log_msg;
        while (log_queue_.try_dequeue(log_msg)) {
            if (log_msg.first) c74::max::post("%s", ("ERROR: " + log_msg.second).c_str());
            else c74::max::post("%s", log_msg.second.c_str());
        }
        std::vector<std::vector<int>> result;
        if (output_queue_.try_dequeue(result)) {
            std::vector<std::vector<int>> temp;
            while (output_queue_.try_dequeue(temp))
                result = std::move(temp);
            if (result.size() == kNumLevels) {
                atoms a2(result[2].begin(), result[2].end());
                level2_out.send(a2);
                atoms a1(result[1].begin(), result[1].end());
                level1_out.send(a1);
                atoms a0(result[0].begin(), result[0].end());
                level0_out.send(a0);
            }
        }
    }

    void start_output_timer() {
        output_timer_.delay(10);
    }

    void stop_output_timer() {
        output_timer_.stop();
    }

    // min-api's error()/post() are only safe to call from the main thread —
    // calling them directly here (this runs on worker_thread_) can throw
    // from inside min-api itself, and an exception escaping a std::thread's
    // entry point is an instant abort(). So log_queue_ carries the message
    // to flush_output(), which the output_timer_ only ever runs on the main
    // thread, and it does the actual error()/post() call from there.
    void load_model(const std::string& path) {
        try {
            session_.reset();
            auto* env = ONNXManager::instance().get_env();
            if (!env) {
                log_queue_.enqueue({true, "ncs.snac_24kh.vq: ONNX Runtime not available"});
                return;
            }
            session_options_.SetIntraOpNumThreads(1);
            session_options_.SetGraphOptimizationLevel(
                GraphOptimizationLevel::ORT_ENABLE_EXTENDED);
            session_ = std::make_unique<Ort::Session>(*env, path.c_str(),
                                                       session_options_);
            ONNXManager::instance().release_env();

            auto input_type = session_->GetInputTypeInfo(0);
            input_name_ = session_->GetInputNameAllocated(0, allocator_).get();
            input_dims_ = input_type.GetTensorTypeAndShapeInfo().GetShape();

            size_t n_out = session_->GetOutputCount();
            output_names_.clear();
            for (size_t i = 0; i < n_out; ++i)
                output_names_.push_back(session_->GetOutputNameAllocated(i, allocator_).get());
            if (output_names_.size() != kNumLevels) {
                log_queue_.enqueue({true, "ncs.snac_24kh.vq: expected " + std::to_string(kNumLevels)
                                            + " codebook outputs, model has " + std::to_string(output_names_.size())});
                model_loaded_ = false;
                return;
            }

            model_loaded_ = true;
            log_queue_.enqueue({false, "ncs.snac_24kh.vq: loaded model (" + path + ")"});
        } catch (const std::exception& ex) {
            log_queue_.enqueue({true, "ncs.snac_24kh.vq: failed to load model — " + std::string(ex.what())});
            model_loaded_ = false;
        }
    }

    // Runs quantize_encodings.onnx on flattened [768 x T] embeddings and
    // returns each level's native-resolution codes as a separate int
    // vector (index 0 = coarsest/stride 4 ... index 2 = finest/stride 1).
    std::vector<std::vector<int>> run_onnx(const std::vector<float>& z) {
        if (!session_ || !model_loaded_) return {};
        try {
            std::vector<int64_t> shape = input_dims_;
            if (!shape.empty() && shape[0] == -1) shape[0] = 1;
            int64_t known = 1;
            for (size_t i = 1; i + 1 < shape.size(); ++i) known *= shape[i];
            int64_t T_b = known > 0 ? static_cast<int64_t>(z.size()) / known
                                     : static_cast<int64_t>(z.size());
            if (!shape.empty() && shape.back() == -1) shape.back() = T_b;

            auto tensor = vector_to_tensor(z, shape, allocator_);
            const char* in_names[] = {input_name_.c_str()};
            std::vector<const char*> out_names;
            for (auto& n : output_names_) out_names.push_back(n.c_str());

            Ort::RunOptions opts;
            auto outputs = session_->Run(opts, in_names, &tensor, 1,
                                          out_names.data(), out_names.size());
            if (outputs.size() != kNumLevels) return {};

            std::vector<std::vector<int>> result(kNumLevels);
            for (int lvl = 0; lvl < kNumLevels; ++lvl) {
                auto raw = tensor_to_vector_i64(outputs[lvl]);
                result[lvl].assign(raw.begin(), raw.end());
            }
            return result;
        } catch (const std::exception&) {}
        return {};
    }
};

MIN_EXTERNAL(NcsSnac_24khVq);
