// -----------------------------------------------------------------------------
// ncs.snac_24kh.vq  —  generated by Max External Template Generator
// -----------------------------------------------------------------------------

#ifdef _WIN32
#include <windows.h>
#endif

#include "c74_min.h"
#include "ext.h"
#include "../include/tsqueue.h"

#include "../include/shared_external_helpers.h"
#include "../include/onnx_helpers.h"
#include <algorithm>
#include <atomic>
#include <chrono>
#include <cmath>
#include <memory>
#include <mutex>
#include <string>
#include <thread>
#include <utility>
#include <vector>

using namespace c74::min;

// SNAC 24kHz quantizer: 3 codebook levels, vq_strides=[4,2,1] (coarsest
// first). quantize_encodings.onnx has 1 input ("z") and 3 outputs
// (codes_0/1/2), each already at its own native temporal resolution
// (T/4, T/2, T) -- each level gets its own outlet, so no zero-order-hold
// expansion/interleaving is needed here.
static constexpr int kNumLevels = 3;

// A single "1-atom send followed by a large-list send" pattern crashed
// Max regardless of size or which outlet was used (see
// ncs.snac_24kh.encode.cpp's kMaxChunkAtoms comment for the full story).
// So ncs.snac_24kh.encode now sends ONE self-describing list per chunk:
//   chunk_index, is_last (0/1), original_length, data...
// on a single outlet -- no separate last/length inlets here either. All
// leading fields are NUMBERS, deliberately no leading symbol: a message
// starting with a symbol is routed by Max as a named message selector,
// not handed to the generic list handler (confirmed by a "doesn't
// understand" error from an earlier symbol-tagged version of this
// format). Codes (this module's own output) are ~768x smaller than
// embeddings and never need chunking, but are still queued and sent ONE
// OUTLET PER TICK (never more than one outlet.send() inside a single
// flush_output() call), as a blanket precaution now that the exact
// trigger condition inside Max's outlet_cache isn't fully understood.
struct PendingSend {
    int outlet_id; // 0 = level0, 1 = level1, 2 = level2
    atoms data;    // original_length, codes...
};

class NcsSnac_24khVq : public object<NcsSnac_24khVq>
{
public:
    MIN_DESCRIPTION     {"SNAC 24kHz residual vector quantizer: embeddings -> per-level codes."};
    MIN_TAGS            {"snac, onnx"};
    MIN_AUTHOR          {"Behzad Haki"};
    inlet<> control_in{ this, "(list/load) embeddings chunk from ncs.snac_24kh.encode, or model path" };
    outlet<> level0_out{ this, "(list) original_length, codes... -- codebook level 0 (coarsest, stride 4)" };
    outlet<> level1_out{ this, "(list) original_length, codes... -- codebook level 1 (stride 2)" };
    outlet<> level2_out{ this, "(list) original_length, codes... -- codebook level 2 (finest, stride 1)" };

    // =====================================================================
    // CONSTRUCTOR / DESTRUCTOR
    // =====================================================================
    NcsSnac_24khVq()
        : output_timer_{this, MIN_FUNCTION { flush_output(); output_timer_.delay(10); return {}; }}
    {
        start_worker();
        start_output_timer();
        // Auto-load the model shipped alongside this external. `load
        // <path>` still works afterwards to point at a different model.
        load_queue_.enqueue(BundleResourceLoader::get_resource_path(
            "models/snac_onnx_exports/24khz/quantize_encodings.onnx"));
    }

    ~NcsSnac_24khVq() {
        stop_worker();
        stop_output_timer();
    }

    // Parses ncs.snac_24kh.encode's self-describing chunk format:
    // chunk_index, is_last (0/1), original_length, data.... Chunks
    // accumulate here; only once is_last=1 arrives is the full reassembled
    // embeddings vector handed to the worker -- the ONNX inference itself
    // always runs on the complete, non-chunked tensor, so there's no
    // chunk-boundary artifact in the quantization.
    // Errors go through log_queue_ (not error() inline) -- this can fire
    // very early during patch load, and calling error() synchronously at
    // that point has crashed Max's console/UI; deferring it to the timer
    // callback avoids that.
    message<> list_msg{this, "list", "Embeddings chunk: chunk_index, is_last, original_length, data...",
        MIN_FUNCTION {
            try {
                // Header is 3 atoms: chunk_index, is_last, original_length.
                if (args.size() < 3) return {};
                bool is_last = (int)args[1] != 0;
                original_length_ = (int)args[2];
                for (size_t i = 3; i < args.size(); ++i)
                    accum_z_.push_back((float)args[i]);
                if (is_last) {
                    input_queue_.enqueue({std::move(accum_z_), original_length_});
                    accum_z_.clear();
                }
            } catch (const std::exception& ex) {
                log_queue_.enqueue({true, "ncs.snac_24kh.vq: list handling failed — " + std::string(ex.what())});
            }
            return {};
        }};

    message<> load{this, "load", "Load an ONNX model (.onnx)",
        MIN_FUNCTION {
            if (args.size() < 1) {
                log_queue_.enqueue({true, "ncs.snac_24kh.vq: load requires a file path"});
                return {};
            }
            load_queue_.enqueue((std::string)args[0]);
            return {};
        }};

// =============================================================================
// PRIVATE
// =============================================================================
private:
    std::thread worker_thread_;
    std::atomic<bool> worker_running_{false};
    std::atomic<bool> stop_{false};

    // Only ever touched from message handlers, i.e. the main thread.
    std::vector<float> accum_z_;
    int original_length_{0};

    tsqueue<std::pair<std::vector<float>, int>> input_queue_;
    tsqueue<PendingSend> output_queue_;
    tsqueue<std::string> load_queue_;
    tsqueue<std::pair<bool,std::string>> log_queue_;

    timer<> output_timer_;

    bool model_loaded_{false};
    std::unique_ptr<Ort::Session> session_;
    Ort::SessionOptions session_options_;
    Ort::AllocatorWithDefaultOptions allocator_;
    std::string input_name_;
    std::vector<int64_t> input_dims_;
    std::vector<std::string> output_names_;

    void start_worker() {
        if (worker_running_.exchange(true)) return;
        stop_ = false;
        worker_thread_ = std::thread([this] { worker_loop(); });
    }

    void stop_worker() {
        stop_ = true;
        input_queue_.shutdown();
        load_queue_.shutdown();
        if (worker_thread_.joinable()) {
            if (worker_thread_.get_id() != std::this_thread::get_id())
                worker_thread_.join();
            else
                worker_thread_.detach();
        }
        worker_running_ = false;
    }

    void worker_loop() {
        while (!stop_) {
            std::string path;
            if (load_queue_.try_dequeue(path))
                load_model(path);
            std::pair<std::vector<float>, int> item;
            if (!input_queue_.wait_dequeue(item, 100))
                continue;
            std::pair<std::vector<float>, int> temp;
            while (input_queue_.try_dequeue(temp))
                item = std::move(temp);
            process(item.first, item.second);
        }
    }

    // Builds and queues one PendingSend per level, level2 first ... level0
    // last, so that when flush_output() drains them one per tick, a
    // downstream ncs.snac_24kh.embedcodes (whose leftmost/level0 inlet is
    // hot) sees its cold level1/level2 inlets updated before the trigger.
    void process(const std::vector<float>& z, int original_length) {
        if (!model_loaded_) {
            log_queue_.enqueue({true, "ncs.snac_24kh.vq: no model loaded"});
            return;
        }
        auto result = run_onnx(z);
        if (result.size() != kNumLevels) {
            log_queue_.enqueue({true, "ncs.snac_24kh.vq: inference failed"});
            return;
        }
        for (int lvl = kNumLevels - 1; lvl >= 0; --lvl) {
            atoms msg;
            msg.reserve(1 + result[lvl].size());
            msg.push_back(original_length);
            for (int v : result[lvl]) msg.push_back(v);
            output_queue_.enqueue({lvl, std::move(msg)});
        }
    }

    // Every crash seen so far traced back to a call to error() -- post()
    // has been reliable throughout. Route everything through post() with
    // an "ERROR:" prefix instead, to avoid whatever error() is doing
    // (likely highlighting the object in the patcher) that's unsafe here.
    // Exactly ONE outlet.send() per tick (see PendingSend comment above).
    void flush_output() {
        std::pair<bool,std::string> log_msg;
        while (log_queue_.try_dequeue(log_msg)) {
            if (log_msg.first) c74::max::post("%s", ("ERROR: " + log_msg.second).c_str());
            else c74::max::post("%s", log_msg.second.c_str());
        }
        PendingSend item;
        if (output_queue_.try_dequeue(item)) {
            if (item.outlet_id == 2) level2_out.send(item.data);
            else if (item.outlet_id == 1) level1_out.send(item.data);
            else level0_out.send(item.data);
        }
    }

    void start_output_timer() {
        output_timer_.delay(10);
    }

    void stop_output_timer() {
        output_timer_.stop();
    }

    // min-api's error()/post() are only safe to call from the main thread —
    // calling them directly here (this runs on worker_thread_) can throw
    // from inside min-api itself, and an exception escaping a std::thread's
    // entry point is an instant abort(). So log_queue_ carries the message
    // to flush_output(), which the output_timer_ only ever runs on the main
    // thread, and it does the actual error()/post() call from there.
    void load_model(const std::string& path) {
        try {
            session_.reset();
            auto* env = ONNXManager::instance().get_env();
            if (!env) {
                log_queue_.enqueue({true, "ncs.snac_24kh.vq: ONNX Runtime not available"});
                return;
            }
            session_options_.SetIntraOpNumThreads(1);
            session_options_.SetGraphOptimizationLevel(
                GraphOptimizationLevel::ORT_ENABLE_EXTENDED);
            session_ = std::make_unique<Ort::Session>(*env, path.c_str(),
                                                       session_options_);
            ONNXManager::instance().release_env();

            auto input_type = session_->GetInputTypeInfo(0);
            input_name_ = session_->GetInputNameAllocated(0, allocator_).get();
            input_dims_ = input_type.GetTensorTypeAndShapeInfo().GetShape();

            size_t n_out = session_->GetOutputCount();
            output_names_.clear();
            for (size_t i = 0; i < n_out; ++i)
                output_names_.push_back(session_->GetOutputNameAllocated(i, allocator_).get());
            if (output_names_.size() != kNumLevels) {
                log_queue_.enqueue({true, "ncs.snac_24kh.vq: expected " + std::to_string(kNumLevels)
                                            + " codebook outputs, model has " + std::to_string(output_names_.size())});
                model_loaded_ = false;
                return;
            }

            model_loaded_ = true;
            log_queue_.enqueue({false, "ncs.snac_24kh.vq: loaded model (" + path + ")"});
        } catch (const std::exception& ex) {
            log_queue_.enqueue({true, "ncs.snac_24kh.vq: failed to load model — " + std::string(ex.what())});
            model_loaded_ = false;
        }
    }

    // Runs quantize_encodings.onnx on flattened [768 x T] embeddings and
    // returns each level's native-resolution codes as a separate int
    // vector (index 0 = coarsest/stride 4 ... index 2 = finest/stride 1).
    std::vector<std::vector<int>> run_onnx(const std::vector<float>& z) {
        if (!session_ || !model_loaded_) return {};
        try {
            std::vector<int64_t> shape = input_dims_;
            if (!shape.empty() && shape[0] == -1) shape[0] = 1;
            int64_t known = 1;
            for (size_t i = 1; i + 1 < shape.size(); ++i) known *= shape[i];
            int64_t T_b = known > 0 ? static_cast<int64_t>(z.size()) / known
                                     : static_cast<int64_t>(z.size());
            if (!shape.empty() && shape.back() == -1) shape.back() = T_b;

            auto tensor = vector_to_tensor(z, shape, allocator_);
            const char* in_names[] = {input_name_.c_str()};
            std::vector<const char*> out_names;
            for (auto& n : output_names_) out_names.push_back(n.c_str());

            Ort::RunOptions opts;
            auto outputs = session_->Run(opts, in_names, &tensor, 1,
                                          out_names.data(), out_names.size());
            if (outputs.size() != kNumLevels) return {};

            std::vector<std::vector<int>> result(kNumLevels);
            for (int lvl = 0; lvl < kNumLevels; ++lvl) {
                auto raw = tensor_to_vector_i64(outputs[lvl]);
                result[lvl].assign(raw.begin(), raw.end());
            }
            return result;
        } catch (const std::exception&) {}
        return {};
    }
};

MIN_EXTERNAL(NcsSnac_24khVq);
