// -----------------------------------------------------------------------------
// ncs.snac_24kh.decode  —  generated by Max External Template Generator
// -----------------------------------------------------------------------------

#ifdef _WIN32
#include <windows.h>
#endif

#include "c74_min.h"
#include "ext.h"
#include "../include/tsqueue.h"

#include "../include/shared_external_helpers.h"
#include "../include/onnx_helpers.h"
#include "../include/buffer_helpers.h"
#include <algorithm>
#include <atomic>
#include <chrono>
#include <cmath>
#include <memory>
#include <mutex>
#include <string>
#include <thread>
#include <utility>
#include <vector>

using namespace c74::min;

// A single "1-atom send followed by a large-list send" pattern crashed
// Max regardless of size or which outlet was used (see
// ncs.snac_24kh.encode.cpp's kMaxChunkAtoms comment for the full story).
// So there's only one inlet here now; ncs.snac_24kh.embedcodes sends its
// (chunked) embeddings as a single self-describing list per chunk, all
// leading fields NUMBERS (a leading symbol gets routed by Max as a named
// message selector, not the generic list handler):
//   chunk_index, is_last (0/1), original_length, data...

class NcsSnac_24khDecode : public object<NcsSnac_24khDecode>
{
public:
    MIN_DESCRIPTION     {"Runs the SNAC 24kHz decoder and writes the result to a named buffer~."};
    MIN_TAGS            {"snac, onnx, audio"};
    MIN_AUTHOR          {"Behzad Haki"};
    inlet<> embeddings_in{ this, "(set/load/list) buffer name, model path, or chunk_index, is_last, original_length, data..." };

    buffer_reference buffer_ref_{ this };

    // @buffername lets the output buffer~ be set as an object-box argument
    // (@buffername myBuf) or attribute message, alongside the 'set'
    // message buffer_reference already provides. An attribute's setter
    // runs immediately at construction with its default value ("" here)
    // -- guard against binding an empty-named buffer, an untested call
    // into Max's buffer subsystem that crashed on patch load.
    attribute<symbol> buffername{ this, "buffername", "", description{"Name of the buffer~ to write to."},
        setter{ MIN_FUNCTION {
            symbol name = (symbol)args[0];
            if (name != symbol(""))
                buffer_ref_.set(name);
            return {args};
        }}};

    // =====================================================================
    // CONSTRUCTOR / DESTRUCTOR
    // =====================================================================
    NcsSnac_24khDecode()
        : output_timer_{this, MIN_FUNCTION { flush_output(); output_timer_.delay(10); return {}; }}
    {
        start_worker();
        start_output_timer();
        // Auto-load the model shipped alongside this external. `load
        // <path>` still works afterwards to point at a different model.
        load_queue_.enqueue(BundleResourceLoader::get_resource_path(
            "models/snac_onnx_exports/24khz/decode_audio.onnx"));
    }

    ~NcsSnac_24khDecode() {
        stop_worker();
        stop_output_timer();
    }

    // Parses ncs.snac_24kh.embedcodes's self-describing chunk format:
    // chunk_index, is_last (0/1), original_length, data.... Chunks
    // accumulate here; only once is_last=1 arrives does decode_audio.onnx
    // actually run, on the full reassembled embeddings -- so there's no
    // chunk-boundary artifact in the decoded audio, chunking is purely a
    // transport concern. Errors go through log_queue_ (not error()
    // inline) -- this can fire very early during patch load, and calling
    // error() synchronously at that point has crashed Max's console/UI;
    // deferring it to the timer callback avoids that.
    message<> list_msg{this, "list", "Embeddings chunk: chunk_index, is_last, original_length, data...",
        MIN_FUNCTION {
            try {
                // Header is 3 atoms: chunk_index, is_last, original_length.
                if (args.size() < 3) return {};
                bool is_last = (int)args[1] != 0;
                int length = (int)args[2];
                for (size_t i = 3; i < args.size(); ++i)
                    accum_embeddings_.push_back((float)args[i]);
                if (is_last) {
                    input_queue_.enqueue({std::move(accum_embeddings_), length});
                    accum_embeddings_.clear();
                }
            } catch (const std::exception& ex) {
                log_queue_.enqueue({true, "ncs.snac_24kh.decode: list handling failed — " + std::string(ex.what())});
            }
            return {};
        }};

    message<> load{this, "load", "Load an ONNX model (.onnx)",
        MIN_FUNCTION {
            if (args.size() < 1) {
                log_queue_.enqueue({true, "ncs.snac_24kh.decode: load requires a file path"});
                return {};
            }
            load_queue_.enqueue((std::string)args[0]);
            return {};
        }};

// =============================================================================
// PRIVATE
// =============================================================================
private:
    std::thread worker_thread_;
    std::atomic<bool> worker_running_{false};
    std::atomic<bool> stop_{false};

    // Only ever touched from message handlers, i.e. the main thread.
    std::vector<float> accum_embeddings_;

    tsqueue<std::pair<std::vector<float>, int>> input_queue_;
    tsqueue<std::pair<std::vector<float>, int>> output_queue_;
    tsqueue<std::string> load_queue_;
    tsqueue<std::pair<bool,std::string>> log_queue_;

    timer<> output_timer_;

    bool model_loaded_{false};
    std::unique_ptr<Ort::Session> session_;
    Ort::SessionOptions session_options_;
    Ort::AllocatorWithDefaultOptions allocator_;
    std::string input_name_;
    std::string output_name_;
    std::vector<int64_t> input_dims_;
    std::vector<int64_t> output_dims_;

    void start_worker() {
        if (worker_running_.exchange(true)) return;
        stop_ = false;
        worker_thread_ = std::thread([this] { worker_loop(); });
    }

    void stop_worker() {
        stop_ = true;
        input_queue_.shutdown();
        load_queue_.shutdown();
        if (worker_thread_.joinable()) {
            if (worker_thread_.get_id() != std::this_thread::get_id())
                worker_thread_.join();
            else
                worker_thread_.detach();
        }
        worker_running_ = false;
    }

    void worker_loop() {
        while (!stop_) {
            std::string path;
            if (load_queue_.try_dequeue(path))
                load_model(path);
            std::pair<std::vector<float>, int> item;
            if (!input_queue_.wait_dequeue(item, 100))
                continue;
            std::pair<std::vector<float>, int> temp;
            while (input_queue_.try_dequeue(temp))
                item = std::move(temp);
            process(item.first, item.second);
        }
    }

    void process(const std::vector<float>& embeddings, int original_length) {
        if (!model_loaded_) {
            log_queue_.enqueue({true, "ncs.snac_24kh.decode: no model loaded"});
            return;
        }
        auto audio = run_onnx(embeddings);
        if (audio.empty()) {
            log_queue_.enqueue({true, "ncs.snac_24kh.decode: inference failed"});
            return;
        }
        output_queue_.enqueue({std::move(audio), original_length});
    }

    // buffer~ access must happen on the main thread -- min-api's
    // buffer_lock wraps Max's buffer_edit_begin/buffer_edit_end, which are
    // not safe to call from an arbitrary spawned std::thread. The worker
    // thread only runs ONNX inference; the write (and the length trim)
    // happens here, since output_timer_ only ever fires on the main
    // thread.
    // Every crash seen so far traced back to a call to error() -- post()
    // has been reliable throughout. Route everything through post() with
    // an "ERROR:" prefix instead, to avoid whatever error() is doing
    // (likely highlighting the object in the patcher) that's unsafe here.
    void flush_output() {
        std::pair<bool,std::string> log_msg;
        while (log_queue_.try_dequeue(log_msg)) {
            if (log_msg.first) c74::max::post("%s", ("ERROR: " + log_msg.second).c_str());
            else c74::max::post("%s", log_msg.second.c_str());
        }
        std::pair<std::vector<float>, int> item;
        if (output_queue_.try_dequeue(item)) {
            auto& audio = item.first;

            // This runs inside Max's own C dispatch loop (via output_timer_)
            // -- an exception escaping it does not unwind cleanly, it hits
            // std::terminate() and takes the whole host process down.
            // write_mono() already catches internally; this wraps the trim
            // and the name/post formatting too, defensively.
            try {
                int trim = item.second;
                if (trim > 0 && static_cast<size_t>(trim) < audio.size())
                    audio.resize(static_cast<size_t>(trim));

                if (!ncs_buffer::write_mono(buffer_ref_, audio)) {
                    c74::max::post("%s", "ERROR: ncs.snac_24kh.decode: output buffer not found — use 'set <name>' first");
                    return;
                }
                std::string msg = "ncs.snac_24kh.decode: wrote " + std::to_string(audio.size())
                                   + " samples to buffer '" + std::string(buffer_ref_.name()) + "'";
                c74::max::post("%s", msg.c_str());
            } catch (const std::exception& ex) {
                c74::max::post("%s", ("ERROR: ncs.snac_24kh.decode: write failed — " + std::string(ex.what())).c_str());
            }
        }
    }

    void start_output_timer() {
        output_timer_.delay(10);
    }

    void stop_output_timer() {
        output_timer_.stop();
    }

    // min-api's error()/post() are only safe to call from the main thread —
    // calling them directly here (this runs on worker_thread_) can throw
    // from inside min-api itself, and an exception escaping a std::thread's
    // entry point is an instant abort(). So log_queue_ carries the message
    // to flush_output(), which the output_timer_ only ever runs on the main
    // thread, and it does the actual error()/post() call from there.
    void load_model(const std::string& path) {
        try {
            session_.reset();
            auto* env = ONNXManager::instance().get_env();
            if (!env) {
                log_queue_.enqueue({true, "ncs.snac_24kh.decode: ONNX Runtime not available"});
                return;
            }
            session_options_.SetIntraOpNumThreads(1);
            session_options_.SetGraphOptimizationLevel(
                GraphOptimizationLevel::ORT_ENABLE_EXTENDED);
            session_ = std::make_unique<Ort::Session>(*env, path.c_str(),
                                                       session_options_);
            ONNXManager::instance().release_env();

            auto input_type = session_->GetInputTypeInfo(0);
            input_name_ = session_->GetInputNameAllocated(0, allocator_).get();
            input_dims_ = input_type.GetTensorTypeAndShapeInfo().GetShape();

            auto output_type = session_->GetOutputTypeInfo(0);
            output_name_ = session_->GetOutputNameAllocated(0, allocator_).get();
            output_dims_ = output_type.GetTensorTypeAndShapeInfo().GetShape();

            model_loaded_ = true;
            log_queue_.enqueue({false, "ncs.snac_24kh.decode: loaded model (" + path + ")"});
        } catch (const std::exception& ex) {
            log_queue_.enqueue({true, "ncs.snac_24kh.decode: failed to load model — " + std::string(ex.what())});
            model_loaded_ = false;
        }
    }

    std::vector<float> run_onnx(const std::vector<float>& input) {
        if (!session_ || !model_loaded_) return {};
        try {
            std::vector<int64_t> shape = input_dims_;
            if (!shape.empty() && shape[0] == -1) shape[0] = 1;
            if (!shape.empty() && shape.back() == -1) {
                // z_q is [B, 768, T] -- the flattened input covers every
                // dim, so the dynamic trailing dim is input.size() divided
                // by the product of the static middle dims (768), not
                // input.size() itself.
                int64_t known = 1;
                for (size_t i = 1; i + 1 < shape.size(); ++i) known *= shape[i];
                shape.back() = known > 0 ? static_cast<int64_t>(input.size()) / known
                                         : static_cast<int64_t>(input.size());
            }

            auto tensor = vector_to_tensor(input, shape, allocator_);
            const char* in_names[]  = {input_name_.c_str()};
            const char* out_names[] = {output_name_.c_str()};
            Ort::RunOptions opts;
            auto outputs = session_->Run(opts, in_names, &tensor, 1,
                                           out_names, 1);
            if (outputs.size() > 0)
                return tensor_to_vector(outputs[0]);
        } catch (const std::exception&) {}
        return {};
    }
};

MIN_EXTERNAL(NcsSnac_24khDecode);
