// -----------------------------------------------------------------------------
// ncs.rt.snac_44kh.encode~  —  generated by Max External Template Generator
// -----------------------------------------------------------------------------

#ifdef _WIN32
#include <windows.h>
#endif

#include "c74_min.h"
#include "ext.h"
#include "../include/tsqueue.h"

#include "../include/shared_external_helpers.h"
#include "../include/onnx_helpers.h"
#include "../include/resample_helpers.h"
#include "../include/chunk_helpers.h"
#include <algorithm>
#include <atomic>
#include <chrono>
#include <cmath>
#include <memory>
#include <mutex>
#include <string>
#include <thread>
#include <utility>
#include <vector>

using namespace c74::min;

// SNAC 44kHz encoder, real-time variant. There is no incremental/cached
// conv-state ONNX graph for SNAC (unlike EnCodec's LSTM h/c) -- the same
// encode_audio_segment.onnx the buffer module uses always runs its whole
// conv stack fresh on whatever's handed to it. So "streaming" here means
// windowed context-trim: each new kBlockSize-sample block is prepended
// with the PREVIOUS block (kContextSize == kBlockSize, one block of real
// trailing audio) before Run(), and only the newly-computed frames
// (covering just the new block) are kept -- the leading, context-derived
// frames are discarded every time. This needs no changes to the
// exported ONNX graph and reuses the exact weights/graph already
// validated in the buffer module; the cost is discarding half the
// compute (context frames) every block, and a latency floor of one block
// (kBlockSize samples @ 44kHz) before the first embeddings can appear.
// Identical network to snac_32kh (only sampling rate and weights
// differ) -- see ncs.rt.snac_24kh.encode_tilde.cpp for the full design
// rationale this module mirrors.
//
// kBlockSize is chosen as one preprocess_pad multiple (12288 samples ==
// hop_length(384) * lcm(vq_strides[0]=8, attn_window_size=32) = 384*32,
// matching ncs.snac_44kh.encode's padding rule) so every block's frame
// count stays aligned with BOTH the VQ stride grouping and the local
// attention window without needing extra padding logic here. This is a
// much bigger block (and latency floor) than snac_24kh's 2048 samples --
// 32k/44k's local attention (window=32) combined with a coarsest VQ
// stride of 8 forces a much larger minimum granularity than 24k's
// conv-only, no-attention architecture.
static constexpr int64_t kHopLength    = 384;
static constexpr int64_t kBlockFrames  = 32;                         // frames per block (== attn_window_size)
static constexpr int64_t kBlockSize    = kHopLength * kBlockFrames;  // 12288 samples
static constexpr int64_t kContextSize  = kBlockSize;                 // one block of trailing context
static constexpr int64_t kLatentDim    = 1024;

// Each block's trimmed output is kLatentDim*kBlockFrames = 32768 floats
// -- a single unchunked Max list message that size is well past the
// crash threshold documented in ncs.snac_24kh.encode.cpp (~15k-20k atoms
// confirmed to crash Max's own outlet_cache/real_outlet_list via a raw
// memmove overflow). snac_24kh's rt~ block (768*4=3072 atoms) never hit
// this and so never needed chunking, but 32k/44k's much larger block
// (32x the frames, 1024 vs 768 channels) does. So data_out here sends
// the SAME messageix/tensor chunked protocol the buffer modules use,
// and ncs.rt.snac_44kh.vq reassembles it -- unlike snac_24kh.rt's plain
// "list" transport.
//
// kMaxChunkAtoms is 12000 here (vs the buffer modules' 4000) -- still a
// comfortable margin below the ~15.4k confirmed-safe / ~15k-20k crash
// zone, but this is a CONTINUOUS real-time stream (a new block every
// kBlockSize/kModelSampleRate seconds, forever), unlike buffer mode's
// occasional bang. flush_output() sends at most one message per 10ms
// timer tick; at 4000 this block took 9 chunks x 2 messages = 18 ticks
// (~180ms) just to relay through THIS one hop, stacking with the same
// cost on ncs.rt.snac_44kh.embedcodes -> ncs.rt.snac_44kh.decode~'s hop
// and the model's own ~279ms block-latency floor -- enough added
// serialization delay to starve decode~'s ring buffer and cause audible
// dropouts. 12000 cuts this to 3 chunks x 2 = 6 ticks (~60ms).
static constexpr size_t kMaxChunkAtoms = 12000;

// The model only works at 44kHz; the live host DSP rate is whatever
// Max's signal chain is running at. Unlike the buffer module's one-shot
// src_simple() call, this runs continuously block after block, so the
// resampler here must carry its filter state across calls (see
// ncs_resample::StreamingResampler) or every block boundary would click.
static constexpr double kModelSampleRate = 44100.0;

// Granularity (in HOST-rate samples) at which incoming audio is handed
// to the streaming resampler -- independent of Max's DSP vector size, so
// behavior doesn't change if the user changes their signal vector size.
static constexpr size_t kHostFlushSamples = 256;

class NcsRtSnac_44khEncode : public object<NcsRtSnac_44khEncode>
    , public sample_operator<1, 0>
{
public:
    MIN_DESCRIPTION     {"Runs the SNAC 44kHz encoder continuously on a live audio signal (windowed context-trim streaming)."};
    MIN_TAGS            {"snac, onnx, audio"};
    MIN_AUTHOR          {"Behzad Haki"};
    inlet<> signal_in{ this, "(signal) audio input" };
    outlet<> data_out{ this, "(messageix/tensor) chunked embeddings block, channel-major [1024 x T], one block per messageix/tensor sequence" };

    // =====================================================================
    // CONSTRUCTOR / DESTRUCTOR
    // =====================================================================
    NcsRtSnac_44khEncode()
        : output_timer_{this, MIN_FUNCTION { flush_output(); output_timer_.delay(10); return {}; }}
    {
        context_.assign(static_cast<size_t>(kContextSize), 0.0f);
        start_worker();
        start_output_timer();
        // Auto-load the model shipped alongside this external -- the
        // SAME encode_audio_segment.onnx the buffer module uses. `load
        // <path>` still works afterwards to point at a different model.
        load_queue_.enqueue(BundleResourceLoader::get_resource_path(
            "models/snac_onnx_exports/44khz/encode_audio_segment.onnx"));
    }

    ~NcsRtSnac_44khEncode() {
        stop_worker();
        stop_output_timer();
    }

    // Normally runs on the AUDIO THREAD only, and only ever from one
    // thread at a time -- but Max recompiles the DSP chain (and
    // re-registers this same perform callback) on every DSP on/off
    // toggle without destroying/recreating this object, and a toggle can
    // land in a narrow window where the previous chain's audio callback
    // hasn't fully quiesced before the new one starts. audio_mutex_
    // guards against that: if operator() is ever (re-)entered
    // concurrently, one call simply waits a few instructions for the
    // other instead of two threads mutating raw_accum_/model_pending_/
    // context_ at once -- which, left unguarded, is exactly the kind of
    // race that corrupts a std::vector's heap-allocated buffer. Never
    // calls into ONNX, min-api's error()/post(), or anything else that
    // can block/allocate unpredictably.
    sample operator()(sample in) {
        std::lock_guard<std::mutex> lock(audio_mutex_);
        double sr = samplerate();
        if (reset_requested_.exchange(false) || sr != last_sr_seen_) {
            resampler_.reset_state();
            raw_accum_.clear();
            model_pending_.clear();
            context_.assign(static_cast<size_t>(kContextSize), 0.0f);
            last_sr_seen_ = sr;
        }

        raw_accum_.push_back(static_cast<float>(in));
        if (raw_accum_.size() >= kHostFlushSamples) {
            double ratio = (sr > 0.0) ? (kModelSampleRate / sr) : 1.0;
            auto resampled = resampler_.process(raw_accum_, ratio);
            raw_accum_.clear();
            model_pending_.insert(model_pending_.end(), resampled.begin(), resampled.end());
        }

        while (model_pending_.size() >= static_cast<size_t>(kBlockSize)) {
            std::vector<float> new_block(model_pending_.begin(), model_pending_.begin() + kBlockSize);
            model_pending_.erase(model_pending_.begin(), model_pending_.begin() + kBlockSize);

            std::vector<float> combined;
            combined.reserve(static_cast<size_t>(kContextSize + kBlockSize));
            combined.insert(combined.end(), context_.begin(), context_.end());
            combined.insert(combined.end(), new_block.begin(), new_block.end());

            // Strict FIFO -- every block in this stream matters, none can
            // be dropped or collapsed (unlike buffer mode's bang-
            // supersedes-bang queues; see ncs.rt.snac_24kh.vq's
            // class-level comment).
            input_queue_.enqueue(std::move(combined));
            context_ = std::move(new_block);
        }
        return 0.0;
    }

    // Clears the streaming context (trailing audio history, resampler
    // filter state, and any not-yet-processed blocks) -- there's no real
    // conv state to reset (SNAC's ONNX graphs aren't stateful), so this
    // just re-primes the windowed context-trim bookkeeping for a fresh
    // stream. Safe to call at any time: reset_requested_ is only ever
    // consumed by the audio thread itself, so there's no race with the
    // buffers it guards (all of which are audio-thread-only).
    message<> reset_msg{this, "reset", "Clear streaming context and any queued (not-yet-encoded) blocks",
        MIN_FUNCTION {
            reset_requested_.store(true);
            input_queue_.clear();
            return {};
        }};

    message<> load{this, "load", "Load an ONNX model (.onnx)",
        MIN_FUNCTION {
            if (args.size() < 1) {
                log_queue_.enqueue({true, "ncs.rt.snac_44kh.encode~: load requires a file path"});
                return {};
            }
            load_queue_.enqueue((std::string)args[0]);
            return {};
        }};

// =============================================================================
// PRIVATE
// =============================================================================
private:
    std::thread worker_thread_;
    std::atomic<bool> worker_running_{false};
    std::atomic<bool> stop_{false};

    tsqueue<std::vector<float>> input_queue_;
    tsqueue<atoms> output_queue_; // one messageix or tensor message per entry
    tsqueue<std::string> load_queue_;
    tsqueue<std::pair<bool,std::string>> log_queue_;

    // Audio-thread-only state (touched exclusively inside operator(),
    // under audio_mutex_ -- see operator()'s comment for why the mutex
    // exists despite this normally being single-threaded).
    std::mutex audio_mutex_;
    ncs_resample::StreamingResampler resampler_;
    std::vector<float> raw_accum_;      // host-rate samples awaiting resample
    std::vector<float> model_pending_;  // resampled (44kHz) samples awaiting a full block
    std::vector<float> context_;        // trailing kContextSize samples from the previous block
    double last_sr_seen_{-1.0};
    std::atomic<bool> reset_requested_{false};

    timer<> output_timer_;

    bool model_loaded_{false};
    std::unique_ptr<Ort::Session> session_;
    Ort::SessionOptions session_options_;
    Ort::AllocatorWithDefaultOptions allocator_;
    std::string input_name_;
    std::string output_name_;
    std::vector<int64_t> input_dims_;
    std::vector<int64_t> output_dims_;

    void start_worker() {
        if (worker_running_.exchange(true)) return;
        stop_ = false;
        worker_thread_ = std::thread([this] { worker_loop(); });
    }

    void stop_worker() {
        stop_ = true;
        input_queue_.shutdown();
        load_queue_.shutdown();
        if (worker_thread_.joinable()) {
            if (worker_thread_.get_id() != std::this_thread::get_id())
                worker_thread_.join();
            else
                worker_thread_.detach();
        }
        worker_running_ = false;
    }

    // Strict FIFO, no collapse-to-latest -- see operator()'s comment.
    void worker_loop() {
        while (!stop_) {
            std::string path;
            if (load_queue_.try_dequeue(path))
                load_model(path);
            std::vector<float> item;
            if (!input_queue_.wait_dequeue(item, 100))
                continue;
            process(item);
        }
    }

    // Runs the full [context(kContextSize) + new(kBlockSize)] window
    // through encode_audio_segment.onnx, then keeps only the LAST
    // kBlockFrames time-steps of the channel-major [1024 x T] output --
    // the frames whose receptive field is anchored in real (context)
    // audio rather than the model's own zero-init edge behavior.
    void process(const std::vector<float>& combined) {
        if (!model_loaded_) {
            log_queue_.enqueue({true, "ncs.rt.snac_44kh.encode~: no model loaded"});
            return;
        }
        auto z = run_onnx(combined);
        if (z.empty()) {
            log_queue_.enqueue({true, "ncs.rt.snac_44kh.encode~: inference failed"});
            return;
        }
        int64_t T_total = static_cast<int64_t>(z.size()) / kLatentDim;
        if (T_total < kBlockFrames) {
            log_queue_.enqueue({true, "ncs.rt.snac_44kh.encode~: unexpected output length"});
            return;
        }
        std::vector<float> trimmed(static_cast<size_t>(kLatentDim * kBlockFrames));
        for (int64_t c = 0; c < kLatentDim; ++c) {
            const float* src = &z[static_cast<size_t>(c * T_total + (T_total - kBlockFrames))];
            std::copy(src, src + kBlockFrames, trimmed.begin() + static_cast<size_t>(c * kBlockFrames));
        }

        // See kMaxChunkAtoms' comment: this block (32768 atoms) is far
        // past the single-list-message crash threshold, so it goes out
        // as the buffer modules' messageix/tensor chunked protocol
        // instead of one big list.
        auto chunks = ncs_chunk::split(trimmed, kMaxChunkAtoms);
        for (size_t i = 0; i < chunks.size(); ++i) {
            bool is_last = (i + 1 == chunks.size());
            int idx = is_last ? -1 : static_cast<int>(i);

            atoms messageix_msg;
            messageix_msg.push_back(symbol("messageix"));
            messageix_msg.push_back(idx);
            output_queue_.enqueue(std::move(messageix_msg));

            atoms tensor_msg;
            tensor_msg.reserve(1 + chunks[i].size());
            tensor_msg.push_back(symbol("tensor"));
            for (float f : chunks[i]) tensor_msg.push_back(f);
            output_queue_.enqueue(std::move(tensor_msg));
        }
    }

    // Every crash seen so far in the buffer modules traced back to a call
    // to error() -- post() has been reliable throughout. Route everything
    // through post() with an "ERROR:" prefix instead. Exactly ONE outlet
    // per tick, same "never seen the exact trigger condition inside
    // Max's outlet_cache" precaution the buffer modules use -- each
    // chunk stream carries its own messageix/tensor header, so
    // interleaving across ticks doesn't affect correctness, only
    // latency.
    void flush_output() {
        std::pair<bool,std::string> log_msg;
        while (log_queue_.try_dequeue(log_msg)) {
            if (log_msg.first) c74::max::post("%s", ("ERROR: " + log_msg.second).c_str());
            else c74::max::post("%s", log_msg.second.c_str());
        }
        atoms out;
        if (output_queue_.try_dequeue(out))
            data_out.send(out);
    }

    void start_output_timer() {
        output_timer_.delay(10);
    }

    void stop_output_timer() {
        output_timer_.stop();
    }

    // min-api's error()/post() are only safe to call from the main thread —
    // calling them directly here (this runs on worker_thread_) can throw
    // from inside min-api itself, and an exception escaping a std::thread's
    // entry point is an instant abort(). So log_queue_ carries the message
    // to flush_output(), which the output_timer_ only ever runs on the main
    // thread, and it does the actual error()/post() call from there.
    void load_model(const std::string& path) {
        try {
            session_.reset();
            auto* env = ONNXManager::instance().get_env();
            if (!env) {
                log_queue_.enqueue({true, "ncs.rt.snac_44kh.encode~: ONNX Runtime not available"});
                return;
            }
            // 4 intra-op threads, not 1: this Run() processes a much
            // bigger window than snac_24kh (24576 samples of context+new
            // through an attention-bearing network) inside a real-time
            // budget of only kBlockSize/kModelSampleRate (~384ms @ 32k,
            // ~279ms @ 44k -- 44k's is the tighter one, same compute for
            // less wall-clock time) before decode~'s ring buffer starves
            // and audio drops out. Single-threaded compute was a
            // leftover from an earlier (later disproven) heap-corruption
            // theory, not a real correctness requirement -- multi-
            // threading the actual bottleneck (compute time vs. budget)
            // directly targets the underrun/dropout problem, unlike the
            // DisableCpuMemArena/DisableMemPattern calls below (kept
            // regardless, still harmless).
            session_options_.SetIntraOpNumThreads(4);
            session_options_.SetGraphOptimizationLevel(
                GraphOptimizationLevel::ORT_ENABLE_EXTENDED);
            // Every ncs.*/ncs.rt.* module shares one process-wide
            // Ort::Env (ONNXManager, shared_external_helpers.h); the
            // default CPU memory arena + memory-pattern planner mutate
            // shared allocator bookkeeping under concurrent Run() calls
            // across sessions on different worker threads. Buffer mode's
            // rare one-shot-bang calls never hit this, but rt~'s
            // continuous Run()-every-block cadence caused a heap
            // corruption inside ONNX Runtime's own mem-pattern planner
            // (confirmed via a crash report: abort() in malloc's
            // free-list checksum check, inside
            // MemPatternPlanner::GenerateMemPattern(), while this
            // module's worker thread was mid-Run()). Disabling both
            // removes that shared/mutated code path; the cost is moot
            // given how small these tensors are.
            session_options_.DisableCpuMemArena();
            session_options_.DisableMemPattern();
            session_ = std::make_unique<Ort::Session>(*env, path.c_str(),
                                                       session_options_);
            ONNXManager::instance().release_env();

            auto input_type = session_->GetInputTypeInfo(0);
            input_name_ = session_->GetInputNameAllocated(0, allocator_).get();
            input_dims_ = input_type.GetTensorTypeAndShapeInfo().GetShape();

            auto output_type = session_->GetOutputTypeInfo(0);
            output_name_ = session_->GetOutputNameAllocated(0, allocator_).get();
            output_dims_ = output_type.GetTensorTypeAndShapeInfo().GetShape();

            model_loaded_ = true;
            log_queue_.enqueue({false, "ncs.rt.snac_44kh.encode~: loaded model (" + path + ")"});
        } catch (const std::exception& ex) {
            log_queue_.enqueue({true, "ncs.rt.snac_44kh.encode~: failed to load model — " + std::string(ex.what())});
            model_loaded_ = false;
        }
    }

    std::vector<float> run_onnx(const std::vector<float>& input) {
        if (!session_ || !model_loaded_) return {};
        try {
            std::vector<int64_t> shape = input_dims_;
            if (!shape.empty() && shape[0] == -1) shape[0] = 1;
            if (!shape.empty() && shape.back() == -1) {
                // audio is [B, 1, T] -- the dynamic trailing dim is
                // input.size() divided by the product of the static
                // middle dims (1 here, but computed generically).
                int64_t known = 1;
                for (size_t i = 1; i + 1 < shape.size(); ++i) known *= shape[i];
                shape.back() = known > 0 ? static_cast<int64_t>(input.size()) / known
                                         : static_cast<int64_t>(input.size());
            }

            auto tensor = vector_to_tensor(input, shape, allocator_);
            const char* in_names[]  = {input_name_.c_str()};
            const char* out_names[] = {output_name_.c_str()};
            Ort::RunOptions opts;
            auto outputs = session_->Run(opts, in_names, &tensor, 1,
                                           out_names, 1);
            if (outputs.size() > 0)
                return tensor_to_vector(outputs[0]);
        } catch (const std::exception&) {}
        return {};
    }
};

MIN_EXTERNAL(NcsRtSnac_44khEncode);
