// -----------------------------------------------------------------------------
// ncs.snac_24kh.embedcodes  —  generated by Max External Template Generator
// -----------------------------------------------------------------------------

#ifdef _WIN32
#include <windows.h>
#endif

#include "c74_min.h"
#include "ext.h"
#include "../include/tsqueue.h"

#include "../include/shared_external_helpers.h"
#include "../include/onnx_helpers.h"
#include "../include/chunk_helpers.h"
#include <algorithm>
#include <atomic>
#include <chrono>
#include <cmath>
#include <memory>
#include <mutex>
#include <string>
#include <thread>
#include <utility>
#include <vector>

using namespace c74::min;

// SNAC 24kHz codebook lookup: 3 levels, vq_strides=[4,2,1] (coarsest
// first). decode_codes.onnx has 3 inputs (codes_0/1/2, each at its own
// native temporal resolution -- matches ncs.snac_24kh.vq's 3 outlets
// directly, no zero-order-hold decoding needed) and 3 outputs (zq_0/1/2),
// each already upsampled (via Tile) to the full base-rate length T but
// NOT summed -- the graph has no Add node, so the cross-level sum happens
// here, with a per-level gain applied before summing.
static constexpr int kNumLevels = 3;

// Codes in (from ncs.snac_24kh.vq, per level) are a single bare
// (headerless) list -- vq never chunks its output, so no frame/last
// protocol is needed there. Embeddings out (to ncs.snac_24kh.decode and
// friends, per level, chunked) mirror ncs.snac_24kh.encode's data_out
// format: a `frameix <index>` message (index -1 = last chunk) immediately
// followed by `tensor <data...>`, both real Max message selectors rather
// than a header baked into a generic list (see
// ncs.snac_24kh.encode.cpp's kMaxChunkAtoms comment for why that matters
// and for the crash history behind chunking at all). total
// original_length is not threaded through here in either direction --
// ncs.snac_24kh.decode gets it directly from ncs.snac_24kh.encode's
// second outlet. flush_output() still sends AT MOST ONE outlet per tick,
// full stop, as a blanket precaution now that the exact trigger
// condition inside Max's outlet_cache isn't fully understood.
static constexpr size_t kMaxChunkAtoms = 4000;

struct EmbedRequest {
    std::vector<int64_t> codes[kNumLevels];
    double scale[kNumLevels];
};

struct PendingSend {
    int outlet_id; // 0 = sum, 1 = level0, 2 = level1, 3 = level2
    atoms data;
};

class NcsSnac_24khEmbedcodes : public object<NcsSnac_24khEmbedcodes>, public CancellableRun
{
public:
    MIN_DESCRIPTION     {"SNAC 24kHz codebook lookup: per-level codes -> summed + per-level quantized embeddings."};
    MIN_TAGS            {"snac, onnx"};
    MIN_AUTHOR          {"Behzad Haki"};
    // Inlet 0 is hot (triggers processing using the most recently cached
    // level1/level2 values); inlets 1-2 are cold (cache only). This
    // matches ncs.snac_24kh.vq, whose outlets fire right-to-left
    // (level2 first, level0 last), so a direct patch cord hookup lands
    // the cold values before the hot trigger arrives.
    inlet<> level0_in{ this, "(list/load) codes... from ncs.snac_24kh.vq level0 -- hot, or model path" };
    inlet<> level1_in{ this, "(list) codes... from ncs.snac_24kh.vq level1 -- cold" };
    inlet<> level2_in{ this, "(list) codes... from ncs.snac_24kh.vq level2 -- cold" };

    // Leftmost outlet is always the sum (each level scaled by its
    // level<N>_scale before summing); the rest are always the raw,
    // unscaled per-level embeddings. Each is a frameix/tensor chunked
    // stream, same format as ncs.snac_24kh.encode's data_out.
    outlet<> sum_out{ this, "(frameix/tensor) summed embeddings chunk (level0_scale*L0 + level1_scale*L1 + level2_scale*L2), channel-major [768 x T]" };
    outlet<> level0_out{ this, "(frameix/tensor) level 0 embeddings chunk, unscaled, channel-major [768 x T]" };
    outlet<> level1_out{ this, "(frameix/tensor) level 1 embeddings chunk, unscaled, channel-major [768 x T]" };
    outlet<> level2_out{ this, "(frameix/tensor) level 2 embeddings chunk, unscaled, channel-major [768 x T]" };

    attribute<number> level0_scale{ this, "level0_scale", 1.0,
        description{"Gain applied to codebook level 0 (coarsest) before summing into the sum outlet. Does not affect the raw level0 outlet."} };
    attribute<number> level1_scale{ this, "level1_scale", 1.0,
        description{"Gain applied to codebook level 1 before summing into the sum outlet. Does not affect the raw level1 outlet."} };
    attribute<number> level2_scale{ this, "level2_scale", 1.0,
        description{"Gain applied to codebook level 2 (finest) before summing into the sum outlet. Does not affect the raw level2 outlet."} };

    // =====================================================================
    // CONSTRUCTOR / DESTRUCTOR
    // =====================================================================
    NcsSnac_24khEmbedcodes()
        : output_timer_{this, MIN_FUNCTION { flush_output(); output_timer_.delay(10); return {}; }}
    {
        start_worker();
        start_output_timer();
        // Auto-load the model shipped alongside this external. `load
        // <path>` still works afterwards to point at a different model.
        load_queue_.enqueue(BundleResourceLoader::get_resource_path(
            "models/snac_onnx_exports/24khz/decode_codes.onnx"));
    }

    ~NcsSnac_24khEmbedcodes() {
        stop_worker();
        stop_output_timer();
    }

    // Parses ncs.snac_24kh.vq's format: a bare (headerless) codes list per
    // level. Errors go through log_queue_ (not error() inline) -- this
    // can fire very early during patch load, and calling error()
    // synchronously at that point has crashed Max's console/UI;
    // deferring it to the timer callback avoids that.
    message<> list_msg{this, "list", "Per-level codes (inlet 0 hot / 1-2 cold)",
        MIN_FUNCTION {
            try {
                std::vector<int64_t> codes(args.size());
                for (size_t i = 0; i < args.size(); ++i)
                    codes[i] = (int64_t)(int)args[i];
                if (inlet == 1) {
                    cached_level1_ = std::move(codes);
                } else if (inlet == 2) {
                    cached_level2_ = std::move(codes);
                } else if (inlet == 0) {
                    // decode_codes.onnx structurally requires all 3 levels
                    // as input (not optional) -- an empty/missing level
                    // (e.g. vq's outlet 1 or 2 never connected here, so
                    // its cache stayed empty) turns into a zero-length
                    // tensor, which ONNX Runtime does not fail on
                    // gracefully. Refuse instead of risking that.
                    if (cached_level1_.empty() || cached_level2_.empty()) {
                        log_queue_.enqueue({true, "ncs.snac_24kh.embedcodes: level1 and/or level2 codes not yet received "
                              "— connect all three of ncs.snac_24kh.vq's outlets to inlets 0-2"});
                        return {};
                    }
                    EmbedRequest req;
                    req.codes[0] = std::move(codes);
                    req.codes[1] = cached_level1_;
                    req.codes[2] = cached_level2_;
                    req.scale[0] = double(level0_scale);
                    req.scale[1] = double(level1_scale);
                    req.scale[2] = double(level2_scale);
                    // A fresh request supersedes whatever the worker is
                    // still doing -- see ncs.snac_24kh.encode's bang_msg
                    // comment for why this cancels rather than waits.
                    cancel_active_run();
                    input_queue_.enqueue(std::move(req));
                }
            } catch (const std::exception& ex) {
                log_queue_.enqueue({true, "ncs.snac_24kh.embedcodes: list handling failed — " + std::string(ex.what())});
            }
            return {};
        }};

    message<> load{this, "load", "Load an ONNX model (.onnx)",
        MIN_FUNCTION {
            if (args.size() < 1) {
                log_queue_.enqueue({true, "ncs.snac_24kh.embedcodes: load requires a file path"});
                return {};
            }
            load_queue_.enqueue((std::string)args[0]);
            return {};
        }};

// =============================================================================
// PRIVATE
// =============================================================================
private:
    std::thread worker_thread_;
    std::atomic<bool> worker_running_{false};
    std::atomic<bool> stop_{false};

    // Only ever touched from message handlers, i.e. the main thread.
    std::vector<int64_t> cached_level1_;
    std::vector<int64_t> cached_level2_;

    tsqueue<EmbedRequest> input_queue_;
    tsqueue<PendingSend> output_queue_;
    tsqueue<std::string> load_queue_;
    tsqueue<std::pair<bool,std::string>> log_queue_;

    timer<> output_timer_;

    bool model_loaded_{false};
    std::unique_ptr<Ort::Session> session_;
    Ort::SessionOptions session_options_;
    Ort::AllocatorWithDefaultOptions allocator_;
    std::vector<std::string> input_names_;
    std::vector<std::string> output_names_;

    void start_worker() {
        if (worker_running_.exchange(true)) return;
        stop_ = false;
        worker_thread_ = std::thread([this] { worker_loop(); });
    }

    void stop_worker() {
        stop_ = true;
        input_queue_.shutdown();
        load_queue_.shutdown();
        if (worker_thread_.joinable()) {
            if (worker_thread_.get_id() != std::this_thread::get_id())
                worker_thread_.join();
            else
                worker_thread_.detach();
        }
        worker_running_ = false;
    }

    void worker_loop() {
        while (!stop_) {
            std::string path;
            if (load_queue_.try_dequeue(path))
                load_model(path);
            EmbedRequest req;
            if (!input_queue_.wait_dequeue(req, 100))
                continue;
            EmbedRequest temp;
            while (input_queue_.try_dequeue(temp))
                req = std::move(temp);
            process(req);
        }
    }

    static void enqueue_chunks(tsqueue<PendingSend>& q, int outlet_id, const std::vector<float>& data,
                                size_t max_chunk_size) {
        auto chunks = ncs_chunk::split(data, max_chunk_size);
        for (size_t i = 0; i < chunks.size(); ++i) {
            bool is_last = (i + 1 == chunks.size());
            int idx = is_last ? -1 : static_cast<int>(i);

            atoms frameix_msg;
            frameix_msg.push_back(symbol("frameix"));
            frameix_msg.push_back(idx);
            q.enqueue({outlet_id, std::move(frameix_msg)});

            atoms tensor_msg;
            tensor_msg.reserve(1 + chunks[i].size());
            tensor_msg.push_back(symbol("tensor"));
            for (float f : chunks[i]) tensor_msg.push_back(f);
            q.enqueue({outlet_id, std::move(tensor_msg)});
        }
    }

    void process(const EmbedRequest& req) {
        if (!model_loaded_) {
            log_queue_.enqueue({true, "ncs.snac_24kh.embedcodes: no model loaded"});
            return;
        }
        auto result = run_onnx(req);
        if (result.empty() || result.size() != kNumLevels + 1) {
            log_queue_.enqueue({true, "ncs.snac_24kh.embedcodes: inference failed"});
            return;
        }
        // result[0]=sum, [1]=level0, [2]=level1, [3]=level2 -- outlet_id
        // matches that same order (0=sum ... 3=level2).
        for (int outlet_id = 0; outlet_id <= kNumLevels; ++outlet_id)
            enqueue_chunks(output_queue_, outlet_id, result[outlet_id], kMaxChunkAtoms);
    }

    // Every crash seen so far traced back to a call to error() -- post()
    // has been reliable throughout. Route everything through post() with
    // an "ERROR:" prefix instead, to avoid whatever error() is doing
    // (likely highlighting the object in the patcher) that's unsafe here.
    // Exactly ONE outlet.send() per tick (see PendingSend comment above)
    // -- each outlet's own chunk stream carries its own frame/last header,
    // so interleaving across outlets/chunks here doesn't affect
    // correctness, only latency.
    void flush_output() {
        std::pair<bool,std::string> log_msg;
        while (log_queue_.try_dequeue(log_msg)) {
            if (log_msg.first) c74::max::post("%s", ("ERROR: " + log_msg.second).c_str());
            else c74::max::post("%s", log_msg.second.c_str());
        }
        PendingSend item;
        if (output_queue_.try_dequeue(item)) {
            switch (item.outlet_id) {
                case 1: level0_out.send(item.data); break;
                case 2: level1_out.send(item.data); break;
                case 3: level2_out.send(item.data); break;
                default: sum_out.send(item.data); break;
            }
        }
    }

    void start_output_timer() {
        output_timer_.delay(10);
    }

    void stop_output_timer() {
        output_timer_.stop();
    }

    // min-api's error()/post() are only safe to call from the main thread —
    // calling them directly here (this runs on worker_thread_) can throw
    // from inside min-api itself, and an exception escaping a std::thread's
    // entry point is an instant abort(). So log_queue_ carries the message
    // to flush_output(), which the output_timer_ only ever runs on the main
    // thread, and it does the actual error()/post() call from there.
    void load_model(const std::string& path) {
        try {
            session_.reset();
            auto* env = ONNXManager::instance().get_env();
            if (!env) {
                log_queue_.enqueue({true, "ncs.snac_24kh.embedcodes: ONNX Runtime not available"});
                return;
            }
            session_options_.SetIntraOpNumThreads(1);
            session_options_.SetGraphOptimizationLevel(
                GraphOptimizationLevel::ORT_ENABLE_EXTENDED);
            session_ = std::make_unique<Ort::Session>(*env, path.c_str(),
                                                       session_options_);
            ONNXManager::instance().release_env();

            size_t n_in = session_->GetInputCount();
            input_names_.clear();
            for (size_t i = 0; i < n_in; ++i)
                input_names_.push_back(session_->GetInputNameAllocated(i, allocator_).get());

            size_t n_out = session_->GetOutputCount();
            output_names_.clear();
            for (size_t i = 0; i < n_out; ++i)
                output_names_.push_back(session_->GetOutputNameAllocated(i, allocator_).get());

            if (input_names_.size() != kNumLevels || output_names_.size() != kNumLevels) {
                log_queue_.enqueue({true, "ncs.snac_24kh.embedcodes: expected " + std::to_string(kNumLevels)
                                            + " inputs/outputs, model has " + std::to_string(input_names_.size())
                                            + " in / " + std::to_string(output_names_.size()) + " out"});
                model_loaded_ = false;
                return;
            }

            model_loaded_ = true;
            log_queue_.enqueue({false, "ncs.snac_24kh.embedcodes: loaded model (" + path + ")"});
        } catch (const std::exception& ex) {
            log_queue_.enqueue({true, "ncs.snac_24kh.embedcodes: failed to load model — " + std::string(ex.what())});
            model_loaded_ = false;
        }
    }

    // Runs decode_codes.onnx on the three native-resolution per-level code
    // sequences and returns 4 flattened [768 x T] embedding vectors:
    // index 0 = sum of all levels (each scaled by req.scale[lvl] first),
    // indices 1-3 = each level's raw, unscaled embedding.
    std::vector<std::vector<float>> run_onnx(const EmbedRequest& req) {
        if (!session_ || !model_loaded_) return {};
        Ort::RunOptions opts;
        register_run(&opts);
        try {
            std::vector<Ort::Value> in_tensors;
            in_tensors.reserve(kNumLevels);
            std::vector<const char*> in_names;
            for (int lvl = 0; lvl < kNumLevels; ++lvl) {
                std::vector<int64_t> shape = {1, static_cast<int64_t>(req.codes[lvl].size())};
                in_tensors.push_back(vector_to_tensor_i64(req.codes[lvl], shape, allocator_));
                in_names.push_back(input_names_[lvl].c_str());
            }
            std::vector<const char*> out_names;
            for (auto& n : output_names_) out_names.push_back(n.c_str());

            auto outputs = session_->Run(opts, in_names.data(), in_tensors.data(), in_tensors.size(),
                                          out_names.data(), out_names.size());
            clear_run();
            if (outputs.size() != kNumLevels) return {};

            std::vector<float> zq[kNumLevels];
            for (int lvl = 0; lvl < kNumLevels; ++lvl)
                zq[lvl] = tensor_to_vector(outputs[lvl]);

            std::vector<float> sum(zq[0].size(), 0.0f);
            for (int lvl = 0; lvl < kNumLevels; ++lvl) {
                if (zq[lvl].size() != sum.size()) return {};
                float s = static_cast<float>(req.scale[lvl]);
                for (size_t i = 0; i < sum.size(); ++i)
                    sum[i] += zq[lvl][i] * s;
            }

            std::vector<std::vector<float>> result;
            result.reserve(kNumLevels + 1);
            result.push_back(std::move(sum));
            for (int lvl = 0; lvl < kNumLevels; ++lvl)
                result.push_back(std::move(zq[lvl]));
            return result;
        } catch (const std::exception&) {
            clear_run();
        }
        return {};
    }
};

MIN_EXTERNAL(NcsSnac_24khEmbedcodes);
