// -----------------------------------------------------------------------------
// ncs.snac_24kh.embedcodes  —  generated by Max External Template Generator
// -----------------------------------------------------------------------------

#ifdef _WIN32
#include <windows.h>
#endif

#include "c74_min.h"
#include "ext.h"
#include "../include/tsqueue.h"

#include "../include/shared_external_helpers.h"
#include "../include/onnx_helpers.h"
#include <algorithm>
#include <atomic>
#include <chrono>
#include <cmath>
#include <memory>
#include <mutex>
#include <string>
#include <thread>
#include <utility>
#include <vector>

using namespace c74::min;

// SNAC 24kHz codebook lookup: 3 levels, vq_strides=[4,2,1] (coarsest
// first). decode_codes.onnx has 3 inputs (codes_0/1/2, each at its own
// native temporal resolution) and 3 outputs (zq_0/1/2), each already
// upsampled (via Tile) to the full base-rate length T but NOT summed --
// the graph has no Add node, so the cross-level sum happens here.
static constexpr int kNumLevels = 3;
static constexpr int64_t kVqStrides[kNumLevels] = {4, 2, 1};

class NcsSnac_24khEmbedcodes : public object<NcsSnac_24khEmbedcodes>
{
public:
    MIN_DESCRIPTION     {"SNAC 24kHz codebook lookup: codes -> summed quantized embeddings."};
    MIN_TAGS            {"snac, onnx"};
    MIN_AUTHOR          {"Behzad Haki"};
    inlet<> control_in{ this, "(list/load) codes from ncs.snac_24kh.vq, or model path" };
    outlet<> result_out{ this, "(list) quantized embeddings, channel-major flattened [768 x T]" };

    // =====================================================================
    // CONSTRUCTOR / DESTRUCTOR
    // =====================================================================
    NcsSnac_24khEmbedcodes()
        : output_timer_{this, MIN_FUNCTION { flush_output(); output_timer_.delay(10); return {}; }}
    {
        start_worker();
        start_output_timer();
        // Auto-load the model shipped alongside this external. `load
        // <path>` still works afterwards to point at a different model.
        load_queue_.enqueue(BundleResourceLoader::get_resource_path(
            "models/snac_onnx_exports/24khz/decode_codes.onnx"));
    }

    ~NcsSnac_24khEmbedcodes() {
        stop_worker();
        stop_output_timer();
    }

    message<> list_msg{this, "list", "Codes to embed (3 ints per base frame, coarsest first)",
        MIN_FUNCTION {
            try {
                std::vector<int64_t> codes(args.size());
                for (size_t i = 0; i < args.size(); ++i)
                    codes[i] = (int64_t)(int)args[i];
                input_queue_.enqueue(std::move(codes));
            } catch (const std::exception& ex) {
                error("ncs.snac_24kh.embedcodes: list handling failed — " + std::string(ex.what()));
            }
            return {};
        }};

    message<> load{this, "load", "Load an ONNX model (.onnx)",
        MIN_FUNCTION {
            if (args.size() < 1) {
                error("ncs.snac_24kh.embedcodes: load requires a file path");
                return {};
            }
            load_queue_.enqueue((std::string)args[0]);
            return {};
        }};

// =============================================================================
// PRIVATE
// =============================================================================
private:
    std::thread worker_thread_;
    std::atomic<bool> worker_running_{false};
    std::atomic<bool> stop_{false};

    tsqueue<std::vector<int64_t>> input_queue_;
    tsqueue<std::vector<float>> output_queue_;
    tsqueue<std::string> load_queue_;
    tsqueue<std::pair<bool,std::string>> log_queue_;

    timer<> output_timer_;

    bool model_loaded_{false};
    std::unique_ptr<Ort::Session> session_;
    Ort::SessionOptions session_options_;
    Ort::AllocatorWithDefaultOptions allocator_;
    std::vector<std::string> input_names_;
    std::vector<std::string> output_names_;

    void start_worker() {
        if (worker_running_.exchange(true)) return;
        stop_ = false;
        worker_thread_ = std::thread([this] { worker_loop(); });
    }

    void stop_worker() {
        stop_ = true;
        input_queue_.shutdown();
        load_queue_.shutdown();
        if (worker_thread_.joinable()) {
            if (worker_thread_.get_id() != std::this_thread::get_id())
                worker_thread_.join();
            else
                worker_thread_.detach();
        }
        worker_running_ = false;
    }

    void worker_loop() {
        while (!stop_) {
            std::string path;
            if (load_queue_.try_dequeue(path))
                load_model(path);
            std::vector<int64_t> input;
            if (!input_queue_.wait_dequeue(input, 100))
                continue;
            std::vector<int64_t> temp;
            while (input_queue_.try_dequeue(temp))
                input = std::move(temp);
            process(input);
        }
    }

    void process(const std::vector<int64_t>& msg) {
        if (!model_loaded_) {
            log_queue_.enqueue({true, "ncs.snac_24kh.embedcodes: no model loaded"});
            return;
        }
        auto result = run_onnx(msg);
        if (result.empty()) {
            log_queue_.enqueue({true, "ncs.snac_24kh.embedcodes: inference failed"});
            return;
        }
        output_queue_.enqueue(std::move(result));
    }

    void flush_output() {
        std::pair<bool,std::string> log_msg;
        while (log_queue_.try_dequeue(log_msg)) {
            if (log_msg.first) error(log_msg.second);
            else c74::max::post("%s", log_msg.second.c_str());
        }
        std::vector<float> result;
        if (output_queue_.try_dequeue(result)) {
            std::vector<float> temp;
            while (output_queue_.try_dequeue(temp))
                result = std::move(temp);
            atoms out_atoms(result.begin(), result.end());
            result_out.send(out_atoms);
        }
    }

    void start_output_timer() {
        output_timer_.delay(10);
    }

    void stop_output_timer() {
        output_timer_.stop();
    }

    // min-api's error()/post() are only safe to call from the main thread —
    // calling them directly here (this runs on worker_thread_) can throw
    // from inside min-api itself, and an exception escaping a std::thread's
    // entry point is an instant abort(). So log_queue_ carries the message
    // to flush_output(), which the output_timer_ only ever runs on the main
    // thread, and it does the actual error()/post() call from there.
    void load_model(const std::string& path) {
        try {
            session_.reset();
            auto* env = ONNXManager::instance().get_env();
            if (!env) {
                log_queue_.enqueue({true, "ncs.snac_24kh.embedcodes: ONNX Runtime not available"});
                return;
            }
            session_options_.SetIntraOpNumThreads(1);
            session_options_.SetGraphOptimizationLevel(
                GraphOptimizationLevel::ORT_ENABLE_EXTENDED);
            session_ = std::make_unique<Ort::Session>(*env, path.c_str(),
                                                       session_options_);
            ONNXManager::instance().release_env();

            size_t n_in = session_->GetInputCount();
            input_names_.clear();
            for (size_t i = 0; i < n_in; ++i)
                input_names_.push_back(session_->GetInputNameAllocated(i, allocator_).get());

            size_t n_out = session_->GetOutputCount();
            output_names_.clear();
            for (size_t i = 0; i < n_out; ++i)
                output_names_.push_back(session_->GetOutputNameAllocated(i, allocator_).get());

            if (input_names_.size() != kNumLevels || output_names_.size() != kNumLevels) {
                log_queue_.enqueue({true, "ncs.snac_24kh.embedcodes: expected " + std::to_string(kNumLevels)
                                            + " inputs/outputs, model has " + std::to_string(input_names_.size())
                                            + " in / " + std::to_string(output_names_.size()) + " out"});
                model_loaded_ = false;
                return;
            }

            model_loaded_ = true;
            log_queue_.enqueue({false, "ncs.snac_24kh.embedcodes: loaded model (" + path + ")"});
        } catch (const std::exception& ex) {
            log_queue_.enqueue({true, "ncs.snac_24kh.embedcodes: failed to load model — " + std::string(ex.what())});
            model_loaded_ = false;
        }
    }

    // Takes the zero-order-held code list (as produced by
    // ncs.snac_24kh.vq -- N ints per base frame, coarsest first), recovers
    // each level's native (non-repeated) code sequence by sampling the
    // first frame of each stride-run, runs decode_codes.onnx to get the
    // three upsampled zq_i tensors, and elementwise-sums them into a
    // single flattened [768 x T] embedding vector.
    std::vector<float> run_onnx(const std::vector<int64_t>& codes_zoh) {
        if (!session_ || !model_loaded_) return {};
        if (codes_zoh.size() % kNumLevels != 0) return {};
        int64_t T_b = static_cast<int64_t>(codes_zoh.size()) / kNumLevels;
        try {
            std::vector<std::vector<int64_t>> native(kNumLevels);
            for (int lvl = 0; lvl < kNumLevels; ++lvl)
                native[lvl].resize(static_cast<size_t>(T_b / kVqStrides[lvl]));
            for (int64_t t = 0; t < T_b; ++t) {
                for (int lvl = 0; lvl < kNumLevels; ++lvl) {
                    if (t % kVqStrides[lvl] == 0)
                        native[lvl][static_cast<size_t>(t / kVqStrides[lvl])] = codes_zoh[t * kNumLevels + lvl];
                }
            }

            std::vector<Ort::Value> in_tensors;
            in_tensors.reserve(kNumLevels);
            std::vector<const char*> in_names;
            for (int lvl = 0; lvl < kNumLevels; ++lvl) {
                std::vector<int64_t> shape = {1, static_cast<int64_t>(native[lvl].size())};
                in_tensors.push_back(vector_to_tensor_i64(native[lvl], shape, allocator_));
                in_names.push_back(input_names_[lvl].c_str());
            }
            std::vector<const char*> out_names;
            for (auto& n : output_names_) out_names.push_back(n.c_str());

            Ort::RunOptions opts;
            auto outputs = session_->Run(opts, in_names.data(), in_tensors.data(), in_tensors.size(),
                                          out_names.data(), out_names.size());
            if (outputs.size() != kNumLevels) return {};

            std::vector<float> zq0 = tensor_to_vector(outputs[0]);
            std::vector<float> sum = zq0;
            for (int lvl = 1; lvl < kNumLevels; ++lvl) {
                auto zqi = tensor_to_vector(outputs[lvl]);
                if (zqi.size() != sum.size()) return {};
                for (size_t i = 0; i < sum.size(); ++i)
                    sum[i] += zqi[i];
            }
            return sum;
        } catch (const std::exception&) {}
        return {};
    }
};

MIN_EXTERNAL(NcsSnac_24khEmbedcodes);
