// -----------------------------------------------------------------------------
// ncs.snac24kh.vq  —  generated by Max External Template Generator
// -----------------------------------------------------------------------------

#ifdef _WIN32
#include <windows.h>
#endif

#include "c74_min.h"
#include "ext.h"
#include "../include/tsqueue.h"

#include "../include/shared_external_helpers.h"
#include "../include/onnx_helpers.h"
#include <algorithm>
#include <atomic>
#include <chrono>
#include <cmath>
#include <memory>
#include <mutex>
#include <string>
#include <thread>
#include <utility>
#include <vector>

using namespace c74::min;

// SNAC 24kHz quantizer: 3 codebook levels, vq_strides=[4,2,1] (coarsest
// first). quantize_encodings.onnx has 1 input ("z") and 3 outputs
// (codes_0/1/2), each already at its own native temporal resolution
// (T/4, T/2, T) -- each level gets its own outlet, so no zero-order-hold
// expansion/interleaving is needed here.
static constexpr int kNumLevels = 3;

// ncs.snac24kh.encode sends chunked embeddings as a `messageix <index>`
// message (index -1 = last chunk) immediately followed by a `tensor
// <data...>` message, both from its single data outlet -- real Max
// message selectors, not a header baked into a generic list, so the
// handlers below get already-header-free args for free. total
// original_length is NOT part of this stream (it never was needed here --
// it's only ever a pass-through for ncs.snac24kh.decode's final trim,
// which now gets it directly from ncs.snac24kh.encode's second outlet).
// Codes (this module's own output) are ~768x smaller than embeddings and
// never need chunking -- sent as a single bare (headerless) list per
// level -- but are still queued and sent ONE OUTLET PER TICK (never more
// than one outlet.send() inside a single flush_output() call), as a
// blanket precaution now that the exact trigger condition inside Max's
// outlet_cache isn't fully understood.
struct PendingSend {
    int outlet_id; // 0 = level0, 1 = level1, 2 = level2
    atoms data;    // codes...
};

class NcsSnac24khVq : public object<NcsSnac24khVq>, public CancellableRun
{
public:
    MIN_DESCRIPTION     {"SNAC 24kHz residual vector quantizer: embeddings -> per-level codes."};
    MIN_TAGS            {"snac, onnx"};
    MIN_AUTHOR          {"Behzad Haki"};
    inlet<> control_in{ this, "(messageix/tensor/load) embeddings chunk from ncs.snac24kh.encode, or model path" };
    outlet<> level0_out{ this, "(list) codes... -- codebook level 0 (coarsest, stride 4)" };
    outlet<> level1_out{ this, "(list) codes... -- codebook level 1 (stride 2)" };
    outlet<> level2_out{ this, "(list) codes... -- codebook level 2 (finest, stride 1)" };

    // =====================================================================
    // CONSTRUCTOR / DESTRUCTOR
    // =====================================================================
    NcsSnac24khVq()
        : output_timer_{this, MIN_FUNCTION { flush_output(); output_timer_.delay(10); return {}; }}
    {
        start_worker();
        start_output_timer();
        // Auto-load the model shipped alongside this external. `load
        // <path>` still works afterwards to point at a different model.
        default_model_path_ = BundleResourceLoader::get_resource_path(
            "models/snac_onnx_exports/24khz/quantize_encodings.onnx");
        load_queue_.enqueue(default_model_path_);
    }

    ~NcsSnac24khVq() {
        stop_worker();
        stop_output_timer();
    }

    // Chunks accumulate here; only once a tensor arrives whose preceding
    // messageix was -1 (the last chunk) is the full reassembled embeddings
    // vector handed to the worker -- the ONNX inference itself always
    // runs on the complete, non-chunked tensor, so there's no
    // chunk-boundary artifact in the quantization.
    // Errors go through log_queue_ (not error() inline) -- this can fire
    // very early during patch load, and calling error() synchronously at
    // that point has crashed Max's console/UI; deferring it to the timer
    // callback avoids that.
    message<> messageix_msg{this, "messageix", "Chunk index (-1 = last chunk)",
        MIN_FUNCTION {
            if (!args.empty())
                pending_is_last_ = ((int)args[0] == -1);
            return {};
        }};

    message<> tensor_msg{this, "tensor", "Embeddings chunk data",
        MIN_FUNCTION {
            try {
                for (auto& a : args)
                    accum_z_.push_back((float)a);
                if (pending_is_last_) {
                    // A fresh reassembled tensor supersedes whatever the
                    // worker is still doing -- see ncs.snac24kh.encode's
                    // bang_msg comment for why this cancels rather than
                    // waits.
                    cancel_active_run();
                    input_queue_.enqueue(std::move(accum_z_));
                    accum_z_.clear();
                    pending_is_last_ = false;
                }
            } catch (const std::exception& ex) {
                log_queue_.enqueue({true, "ncs.snac24kh.vq: tensor handling failed — " + std::string(ex.what())});
            }
            return {};
        }};

    message<> load{this, "load", "Load an ONNX model (.onnx)",
        MIN_FUNCTION {
            if (args.size() < 1) {
                log_queue_.enqueue({true, "ncs.snac24kh.vq: load requires a file path"});
                return {};
            }
            load_queue_.enqueue((std::string)args[0]);
            return {};
        }};

// =============================================================================
// PRIVATE
// =============================================================================
private:
    std::thread worker_thread_;
    std::atomic<bool> worker_running_{false};
    std::atomic<bool> stop_{false};

    // Only ever touched from message handlers, i.e. the main thread.
    std::vector<float> accum_z_;
    bool pending_is_last_{false};

    tsqueue<std::vector<float>> input_queue_;
    tsqueue<PendingSend> output_queue_;
    tsqueue<std::string> load_queue_;
    tsqueue<std::pair<bool,std::string>> log_queue_;

    timer<> output_timer_;

    bool model_loaded_{false};
    std::string default_model_path_;
    std::unique_ptr<Ort::Session> session_;
    Ort::SessionOptions session_options_;
    Ort::AllocatorWithDefaultOptions allocator_;
    std::string input_name_;
    std::vector<int64_t> input_dims_;
    std::vector<std::string> output_names_;

    void start_worker() {
        if (worker_running_.exchange(true)) return;
        stop_ = false;
        worker_thread_ = std::thread([this] { worker_loop(); });
    }

    void stop_worker() {
        stop_ = true;
        input_queue_.shutdown();
        load_queue_.shutdown();
        if (worker_thread_.joinable()) {
            if (worker_thread_.get_id() != std::this_thread::get_id())
                worker_thread_.join();
            else
                worker_thread_.detach();
        }
        worker_running_ = false;
    }

    void worker_loop() {
        while (!stop_) {
            std::string path;
            if (load_queue_.try_dequeue(path))
                load_model(path);
            std::vector<float> item;
            if (!input_queue_.wait_dequeue(item, 100))
                continue;
            std::vector<float> temp;
            while (input_queue_.try_dequeue(temp))
                item = std::move(temp);
            process(item);
        }
    }

    // Builds and queues one PendingSend per level, level2 first ... level0
    // last, so that when flush_output() drains them one per tick, a
    // downstream ncs.snac24kh.embedcodes (whose leftmost/level0 inlet is
    // hot) sees its cold level1/level2 inlets updated before the trigger.
    void process(const std::vector<float>& z) {
        if (!model_loaded_) {
            log_queue_.enqueue({true, "ncs.snac24kh.vq: no model loaded"});
            return;
        }
        auto result = run_onnx(z);
        if (result.size() != kNumLevels) {
            log_queue_.enqueue({true, "ncs.snac24kh.vq: inference failed"});
            return;
        }
        for (int lvl = kNumLevels - 1; lvl >= 0; --lvl) {
            atoms msg;
            msg.reserve(result[lvl].size());
            for (int v : result[lvl]) msg.push_back(v);
            output_queue_.enqueue({lvl, std::move(msg)});
        }
    }

    // Every crash seen so far traced back to a call to error() -- post()
    // has been reliable throughout. Route everything through post() with
    // an "ERROR:" prefix instead, to avoid whatever error() is doing
    // (likely highlighting the object in the patcher) that's unsafe here.
    // Exactly ONE outlet.send() per tick (see PendingSend comment above).
    void flush_output() {
        std::pair<bool,std::string> log_msg;
        while (log_queue_.try_dequeue(log_msg)) {
            if (log_msg.first) c74::max::post("%s", ("ERROR: " + log_msg.second).c_str());
            else c74::max::post("%s", log_msg.second.c_str());
        }
        PendingSend item;
        if (output_queue_.try_dequeue(item)) {
            if (item.outlet_id == 2) level2_out.send(item.data);
            else if (item.outlet_id == 1) level1_out.send(item.data);
            else level0_out.send(item.data);
        }
    }

    void start_output_timer() {
        output_timer_.delay(10);
    }

    void stop_output_timer() {
        output_timer_.stop();
    }

    // min-api's error()/post() are only safe to call from the main thread —
    // calling them directly here (this runs on worker_thread_) can throw
    // from inside min-api itself, and an exception escaping a std::thread's
    // entry point is an instant abort(). So log_queue_ carries the message
    // to flush_output(), which the output_timer_ only ever runs on the main
    // thread, and it does the actual error()/post() call from there.
    void load_model(const std::string& path) {
        try {
            session_.reset();
            auto* env = ONNXManager::instance().get_env();
            if (!env) {
                log_queue_.enqueue({true, "ncs.snac24kh.vq: ONNX Runtime not available"});
                return;
            }
            session_options_.SetIntraOpNumThreads(1);
            session_options_.SetGraphOptimizationLevel(
                GraphOptimizationLevel::ORT_ENABLE_EXTENDED);
            session_ = std::make_unique<Ort::Session>(*env, path.c_str(),
                                                       session_options_);
            ONNXManager::instance().release_env();

            auto input_type = session_->GetInputTypeInfo(0);
            input_name_ = session_->GetInputNameAllocated(0, allocator_).get();
            input_dims_ = input_type.GetTensorTypeAndShapeInfo().GetShape();

            size_t n_out = session_->GetOutputCount();
            output_names_.clear();
            for (size_t i = 0; i < n_out; ++i)
                output_names_.push_back(session_->GetOutputNameAllocated(i, allocator_).get());
            if (output_names_.size() != kNumLevels) {
                log_queue_.enqueue({true, "ncs.snac24kh.vq: expected " + std::to_string(kNumLevels)
                                            + " codebook outputs, model has " + std::to_string(output_names_.size())});
                model_loaded_ = false;
                return;
            }

            model_loaded_ = true;
        } catch (const std::exception& ex) {
            log_queue_.enqueue({true, "ncs.snac24kh.vq: failed to load model (" + path + ") — "
                                        + std::string(ex.what()) + ". Models are expected at "
                                        + default_model_path_ + "."});
            model_loaded_ = false;
        }
    }

    // Runs quantize_encodings.onnx on flattened [768 x T] embeddings and
    // returns each level's native-resolution codes as a separate int
    // vector (index 0 = coarsest/stride 4 ... index 2 = finest/stride 1).
    std::vector<std::vector<int>> run_onnx(const std::vector<float>& z) {
        if (!session_ || !model_loaded_) return {};
        Ort::RunOptions opts;
        register_run(&opts);
        try {
            std::vector<int64_t> shape = input_dims_;
            if (!shape.empty() && shape[0] == -1) shape[0] = 1;
            int64_t known = 1;
            for (size_t i = 1; i + 1 < shape.size(); ++i) known *= shape[i];
            int64_t T_b = known > 0 ? static_cast<int64_t>(z.size()) / known
                                     : static_cast<int64_t>(z.size());
            if (!shape.empty() && shape.back() == -1) shape.back() = T_b;

            auto tensor = vector_to_tensor(z, shape, allocator_);
            const char* in_names[] = {input_name_.c_str()};
            std::vector<const char*> out_names;
            for (auto& n : output_names_) out_names.push_back(n.c_str());

            auto outputs = session_->Run(opts, in_names, &tensor, 1,
                                          out_names.data(), out_names.size());
            clear_run();
            if (outputs.size() != kNumLevels) return {};

            std::vector<std::vector<int>> result(kNumLevels);
            for (int lvl = 0; lvl < kNumLevels; ++lvl) {
                auto raw = tensor_to_vector_i64(outputs[lvl]);
                result[lvl].assign(raw.begin(), raw.end());
            }
            return result;
        } catch (const std::exception&) {
            clear_run();
        }
        return {};
    }
};

MIN_EXTERNAL(NcsSnac24khVq);
