// -----------------------------------------------------------------------------
// ncs.rt.snac44kh.decode~  —  generated by Max External Template Generator
// -----------------------------------------------------------------------------

#ifdef _WIN32
#include <windows.h>
#endif

#include "c74_min.h"
#include "ext.h"
#include "../include/tsqueue.h"

#include "../include/shared_external_helpers.h"
#include "../include/onnx_helpers.h"
#include "../include/resample_helpers.h"
#include <algorithm>
#include <atomic>
#include <chrono>
#include <cmath>
#include <memory>
#include <mutex>
#include <string>
#include <thread>
#include <utility>
#include <vector>

using namespace c74::min;

// SNAC 44kHz decoder, real-time variant. Mirrors ncs.rt.snac44kh.encode~'s
// windowed context-trim approach (see that file's class comment, and
// ncs.rt.snac24kh.decode_tilde.cpp for the full rationale: no
// incremental/cached-state ONNX graph exists for SNAC, so decode_audio.onnx
// -- the SAME graph the buffer module uses -- runs its whole conv stack
// fresh on [context + new] every block, and only the newly-computed
// audio is kept). Two differences from encode~:
//
// 1. The "new" unit here is a MESSAGE (quantized embeddings from
//    ncs.rt.snac44kh.embedcodes), not a signal -- so the context
//    bookkeeping lives in the "list" message handler (main thread)
//    instead of operator() (audio thread).
// 2. Decoded audio must become a continuous SIGNAL. On top of the
//    context-trim (which addresses correctness -- the retained frames'
//    receptive field is anchored in real preceding audio), this also
//    applies a short causal overlap-add crossfade (kOlaSamples) purely
//    as a numerical safety net against residual seam clicks. The
//    crossfade looks BACKWARD into the context region (never forward),
//    so it adds no algorithmic latency beyond the context window itself.
// Identical network to snac32kh (only sampling rate and weights
// differ).
static constexpr int64_t kHopLength     = 384;
static constexpr int64_t kBlockFrames   = 32;                         // expected frames per block (== attn_window_size)
static constexpr int64_t kContextFrames = kBlockFrames;               // one block of trailing zq context
static constexpr int64_t kLatentDim     = 1024;
static constexpr int64_t kOlaSamples    = 256;                        // ~5.8ms @ 44.1kHz crossfade

static constexpr double kModelSampleRate = 44100.0;

// Real-time duration one block of NEW audio represents -- the divisor
// for @monitor_rtf's real-time factor (see PerformanceMonitorScope in
// shared_external_helpers.h). Unlike encode~, no separate resample-time
// folding is needed here: decode_resampler_.process() already runs
// inside process() (see its call site below), so this scope's own
// elapsed time already covers Run() + OLA + resampling in full.
static constexpr double kBlockDurationMs = static_cast<double>(kBlockFrames * kHopLength) / kModelSampleRate * 1000.0;

struct DecodeJob {
    std::vector<float> combined; // channel-major [1024 x (kContextFrames+T_block)]
    int64_t t_block{0};          // number of NEW frames appended this call
    double host_sr{0.0};         // host DSP samplerate at the moment this block arrived
};

class NcsRtSnac44khDecode : public object<NcsRtSnac44khDecode>
    , public sample_operator<0, 1>
{
public:
    MIN_DESCRIPTION     {"Runs the SNAC 44kHz decoder continuously from a streamed quantized-embeddings message (windowed context-trim streaming)."};
    MIN_TAGS            {"snac, onnx, audio"};
    MIN_AUTHOR          {"Behzad Haki"};
    inlet<> embeddings_in{ this, "(messageix/tensor/load/reset) quantized embeddings chunk from ncs.rt.snac44kh.embedcodes, channel-major [1024 x T], or model path" };
    outlet<> signal_out{ this, "(signal) audio output", "signal" };
    // Declarative thread-safe outlet (see min-api's GuideToThreading,
    // "High-Level Outlet Threading Specification"): calls made from the
    // audio thread are automatically deferred to the scheduler thread and
    // delivered in order, so operator() can call .send() directly with no
    // manual timer/queue plumbing of its own.
    outlet<thread_check::scheduler, thread_action::fifo> underrun_out{
        this, "(bang) underrun state changed -- entering underrun (silence) or recovering from it" };

    // Number of decoded blocks to accumulate in the output queue before
    // (re)starting playback. 0 (default) disables this -- audio plays as
    // soon as the first block is ready, identical to prior behavior.
    // Raising it trades added startup/resume latency (N blocks, i.e.
    // N * ~279ms@44k) for headroom against transient processing
    // slowdowns: a reserve this deep has to be exhausted, not just
    // momentarily late, before playback runs dry.
    attribute<int> prebuffer_blocks{ this, "prebuffer_blocks", 0,
        description{"Number of decoded blocks to accumulate before playback starts (or resumes after an underrun), absorbing transient processing slowdowns at the cost of added latency. 0 (default) disables prebuffering."} };

    // Declarative thread-safe outlet, same pattern as underrun_out above:
    // process() runs on worker_thread_, not the main thread.
    outlet<thread_check::scheduler, thread_action::fifo> timing_out{
        this, "(float) real-time factor or process time in ms, per @monitor_rtf, emitted on every block" };

    attribute<bool> monitor_rtf{ this, "monitor_rtf", true,
        description{"Always emits this module's per-block cost (Run() plus OLA plus resampling) out the rightmost outlet. On (default): emitted as a real-time factor (elapsed/block-duration; >=1.0 means this stage alone can't keep up). Off: emitted as raw milliseconds."} };

    // =====================================================================
    // CONSTRUCTOR / DESTRUCTOR
    // =====================================================================
    NcsRtSnac44khDecode()
        : output_timer_{this, MIN_FUNCTION { flush_output(); output_timer_.delay(10); return {}; }}
    {
        context_zq_.assign(static_cast<size_t>(kLatentDim * kContextFrames), 0.0f);
        start_worker();
        start_output_timer();
        // Auto-load the model shipped alongside this external -- the
        // SAME decode_audio.onnx the buffer module uses. `load <path>`
        // still works afterwards to point at a different model.
        default_model_path_ = BundleResourceLoader::get_resource_path(
            "models/snac_onnx_exports/44khz/decode_audio.onnx");
        load_queue_.enqueue(default_model_path_);
    }

    ~NcsRtSnac44khDecode() {
        stop_worker();
        stop_output_timer();
    }

    // Normally runs on the AUDIO THREAD only, and only ever from one
    // thread at a time -- but Max recompiles the DSP chain (and
    // re-registers this same perform callback) on every DSP on/off
    // toggle without destroying/recreating this object, and a toggle can
    // land in a narrow window where the previous chain's audio callback
    // hasn't fully quiesced before the new one starts. audio_mutex_
    // guards against that: if operator() is ever (re-)entered
    // concurrently, one call simply waits a few instructions for the
    // other instead of two threads mutating output_chunk_/output_pos_ at
    // once -- which, left unguarded, is exactly the kind of race that
    // corrupts a std::vector's heap-allocated buffer. Never blocks,
    // never calls into ONNX, or anything else that can lock/allocate
    // unpredictably (log_queue_.enqueue() is the same brief queue-push
    // the rest of this codebase already treats as audio-thread-safe).
    sample operator()() {
        std::lock_guard<std::mutex> lock(audio_mutex_);
        if (playback_reset_pending_.exchange(false)) {
            output_chunk_.clear();
            output_pos_ = 0;
            std::vector<float> discard;
            while (output_queue_.try_dequeue(discard)) {}
            prebuffering_ = true;
        }
        // Pre-roll: while prebuffering, hold silence without consuming
        // from output_queue_ until it holds prebuffer_blocks worth of
        // decoded chunks (0 -- the default -- is always satisfied, so
        // this is a no-op unless the attribute is raised). output_queue_
        // is only touched here and just below via try_dequeue -- both
        // already-established audio-thread-safe brief-lock operations
        // (see the class comment above operator()).
        if (prebuffering_) {
            if (output_pos_ >= output_chunk_.size()
                && output_queue_.size() < static_cast<size_t>(std::max(0, static_cast<int>(prebuffer_blocks))))
                return 0.0;
            prebuffering_ = false;
        }
        // Serve samples from the current decoded chunk; when it runs
        // out, pull the next available chunk from the worker thread.
        if (output_pos_ >= output_chunk_.size()) {
            std::vector<float> next;
            if (output_queue_.try_dequeue(next)) {
                output_chunk_ = std::move(next);
                output_pos_ = 0;
            }
        }
        if (output_pos_ < output_chunk_.size()) {
            if (was_underrun_) {
                was_underrun_ = false;
                notify_underrun_transition();
            }
            return output_chunk_[output_pos_++];
        }
        // Underrun: nothing decoded yet -- output silence rather than
        // block waiting on the worker. Re-arms prebuffering (if enabled)
        // so playback resumes with a fresh reserve instead of immediately
        // racing the worker again one sample at a time.
        if (!was_underrun_) {
            was_underrun_ = true;
            notify_underrun_transition();
            prebuffering_ = true;
        }
        return 0.0;
    }

    // ncs.rt.snac44kh.embedcodes sends its sum_out embeddings as a
    // chunked `messageix <index>` (index -1 = last chunk) immediately
    // followed by `tensor <data...>`, both real Max message selectors --
    // the same protocol the buffer modules use, needed here (unlike
    // snac24kh's rt~ plain "list") because a 32k/44k block (32768
    // atoms) is well past the single-list-message crash threshold
    // documented in ncs.snac24kh.encode.cpp. Once the last chunk
    // arrives, this builds the call's [context + new] window, hands it
    // to the worker, then updates the trailing context to the last
    // kContextFrames frames of that same window (so it's always real
    // audio history, whether it came from the previous new block or --
    // if T is ever smaller than kContextFrames -- partly from the
    // context before that).
    message<> messageix_msg{this, "messageix", "Chunk index (-1 = last chunk)",
        MIN_FUNCTION {
            if (!args.empty())
                pending_is_last_ = ((int)args[0] == -1);
            return {};
        }};

    message<> tensor_msg{this, "tensor", "Quantized embeddings chunk data",
        MIN_FUNCTION {
            try {
                for (auto& a : args)
                    accum_embeddings_.push_back((float)a);
                if (!pending_is_last_)
                    return {};
                std::vector<float>& new_zq = accum_embeddings_;
                int64_t T_block = static_cast<int64_t>(new_zq.size()) / kLatentDim;
                if (T_block <= 0 || T_block * kLatentDim != static_cast<int64_t>(new_zq.size())) {
                    log_queue_.enqueue({true, "ncs.rt.snac44kh.decode~: embeddings block size is not a multiple of 1024 channels"});
                    accum_embeddings_.clear();
                    pending_is_last_ = false;
                    return {};
                }

                int64_t T_in = kContextFrames + T_block;
                std::vector<float> combined(static_cast<size_t>(kLatentDim * T_in));
                for (int64_t c = 0; c < kLatentDim; ++c) {
                    float* dst = &combined[static_cast<size_t>(c * T_in)];
                    std::copy(context_zq_.begin() + static_cast<size_t>(c * kContextFrames),
                              context_zq_.begin() + static_cast<size_t>(c * kContextFrames + kContextFrames),
                              dst);
                    std::copy(new_zq.begin() + static_cast<size_t>(c * T_block),
                              new_zq.begin() + static_cast<size_t>(c * T_block + T_block),
                              dst + kContextFrames);
                }

                // Strict FIFO -- every block in this stream matters, none
                // can be dropped or collapsed (see ncs.rt.snac24kh.vq's
                // class-level comment).
                input_queue_.enqueue({combined, T_block, samplerate()});

                std::vector<float> new_context(static_cast<size_t>(kLatentDim * kContextFrames));
                for (int64_t c = 0; c < kLatentDim; ++c) {
                    const float* src = &combined[static_cast<size_t>(c * T_in + (T_in - kContextFrames))];
                    std::copy(src, src + kContextFrames, new_context.begin() + static_cast<size_t>(c * kContextFrames));
                }
                context_zq_ = std::move(new_context);

                accum_embeddings_.clear();
                pending_is_last_ = false;
            } catch (const std::exception& ex) {
                log_queue_.enqueue({true, "ncs.rt.snac44kh.decode~: tensor handling failed — " + std::string(ex.what())});
                accum_embeddings_.clear();
                pending_is_last_ = false;
            }
            return {};
        }};

    // Clears the streaming context (trailing zq history, crossfade tail,
    // resampler filter state, currently-playing/queued audio, and any
    // not-yet-decoded blocks) -- there's no real conv state to reset
    // (SNAC's ONNX graphs aren't stateful), so this just re-primes the
    // windowed context-trim and OLA bookkeeping for a fresh stream.
    // context_zq_/accum_embeddings_/pending_is_last_ are all main-thread-
    // owned (touched only here and in messageix_msg/tensor_msg, both on
    // the main thread) so they're safe to clear directly; the worker-
    // and audio-thread-owned pieces go through their own atomic flags,
    // consumed by the thread that actually owns them.
    message<> reset_msg{this, "reset", "Clear streaming context, crossfade tail, and any queued/buffered audio",
        MIN_FUNCTION {
            context_zq_.assign(static_cast<size_t>(kLatentDim * kContextFrames), 0.0f);
            accum_embeddings_.clear();
            pending_is_last_ = false;
            input_queue_.clear();
            worker_reset_pending_.store(true);
            playback_reset_pending_.store(true);
            return {};
        }};

    message<> load{this, "load", "Load an ONNX model (.onnx)",
        MIN_FUNCTION {
            if (args.size() < 1) {
                log_queue_.enqueue({true, "ncs.rt.snac44kh.decode~: load requires a file path"});
                return {};
            }
            load_queue_.enqueue((std::string)args[0]);
            return {};
        }};

// =============================================================================
// PRIVATE
// =============================================================================
private:
    std::thread worker_thread_;
    std::atomic<bool> worker_running_{false};
    std::atomic<bool> stop_{false};

    // Main-thread-only (touched only in messageix_msg/tensor_msg/reset_msg).
    std::vector<float> context_zq_;
    std::vector<float> accum_embeddings_;
    bool pending_is_last_{false};

    tsqueue<DecodeJob> input_queue_;
    tsqueue<std::vector<float>> output_queue_;
    tsqueue<std::string> load_queue_;
    tsqueue<std::pair<bool,std::string>> log_queue_;

    // Audio-thread-only (touched only inside operator(), under
    // audio_mutex_ -- see operator()'s comment for why the mutex exists
    // despite this normally being single-threaded).
    std::mutex audio_mutex_;
    std::vector<float> output_chunk_;
    size_t output_pos_{0};
    bool was_underrun_{false};
    bool prebuffering_{true};
    std::chrono::steady_clock::time_point last_underrun_event_{};
    std::atomic<bool> playback_reset_pending_{false};

    // Worker-thread-only (touched only inside process(), which only ever
    // runs sequentially on worker_thread_).
    ncs_resample::StreamingResampler decode_resampler_;
    double last_decode_sr_seen_{-1.0};
    std::vector<float> held_tail_; // last kOlaSamples of the previous block's own output, not yet emitted
    std::atomic<bool> worker_reset_pending_{false};

    timer<> output_timer_;

    bool model_loaded_{false};
    std::string default_model_path_;
    std::unique_ptr<Ort::Session> session_;
    Ort::SessionOptions session_options_;
    Ort::AllocatorWithDefaultOptions allocator_;
    std::string input_name_;
    std::string output_name_;
    std::vector<int64_t> input_dims_;
    std::vector<int64_t> output_dims_;

    void start_worker() {
        if (worker_running_.exchange(true)) return;
        stop_ = false;
        worker_thread_ = std::thread([this] { worker_loop(); });
    }

    void stop_worker() {
        stop_ = true;
        input_queue_.shutdown();
        load_queue_.shutdown();
        if (worker_thread_.joinable()) {
            if (worker_thread_.get_id() != std::this_thread::get_id())
                worker_thread_.join();
            else
                worker_thread_.detach();
        }
        worker_running_ = false;
    }

    // Strict FIFO, no collapse-to-latest -- see the class-level comment.
    void worker_loop() {
        while (!stop_) {
            std::string path;
            if (load_queue_.try_dequeue(path))
                load_model(path);
            if (worker_reset_pending_.exchange(false)) {
                held_tail_.clear();
                decode_resampler_.reset_state();
                last_decode_sr_seen_ = -1.0;
            }
            DecodeJob item;
            if (!input_queue_.wait_dequeue(item, 100))
                continue;
            process(item);
        }
    }

    // Runs the full [context(kContextFrames) + new(T_block)] window
    // through decode_audio.onnx, keeps the tail (new samples plus
    // kOlaSamples of look-back into the context-derived output),
    // crossfades that look-back region against the previous call's held
    // tail (causal OLA -- no added latency beyond the context window),
    // and resamples the result to the host's live DSP rate with a
    // persistent-state resampler (unlike the buffer module's one-shot
    // call, this runs every block, so filter continuity across blocks
    // matters).
    void process(const DecodeJob& job) {
        PerformanceMonitorScope<decltype(timing_out)> perf_scope(bool(monitor_rtf), timing_out, kBlockDurationMs);

        if (!model_loaded_) {
            log_queue_.enqueue({true, "ncs.rt.snac44kh.decode~: no model loaded"});
            return;
        }
        auto audio = run_onnx(job.combined);
        if (audio.empty()) {
            log_queue_.enqueue({true, "ncs.rt.snac44kh.decode~: inference failed"});
            return;
        }
        int64_t total_samples = static_cast<int64_t>(audio.size());
        int64_t hop = job.t_block * kHopLength;
        int64_t boundary = total_samples - hop; // == kContextFrames*kHopLength in the normal case
        if (boundary < 0 || hop <= 0) {
            log_queue_.enqueue({true, "ncs.rt.snac44kh.decode~: unexpected output length"});
            return;
        }
        int64_t ola = std::min<int64_t>(kOlaSamples, boundary);
        int64_t keep_start = boundary - ola;

        std::vector<float> kept(audio.begin() + keep_start, audio.end()); // length hop+ola
        std::vector<float> finalized(static_cast<size_t>(hop));
        for (int64_t i = 0; i < ola; ++i) {
            float t = (ola > 1) ? static_cast<float>(i) / static_cast<float>(ola - 1) : 1.0f;
            float old_v = (i < static_cast<int64_t>(held_tail_.size())) ? held_tail_[static_cast<size_t>(i)] : 0.0f;
            finalized[static_cast<size_t>(i)] = old_v * (1.0f - t) + kept[static_cast<size_t>(i)] * t;
        }
        if (hop > ola)
            std::copy(kept.begin() + ola, kept.begin() + hop, finalized.begin() + ola);
        held_tail_.assign(kept.begin() + hop, kept.end()); // length ola, held for the NEXT call

        if (job.host_sr != last_decode_sr_seen_) {
            decode_resampler_.reset_state();
            last_decode_sr_seen_ = job.host_sr;
        }
        double ratio = (job.host_sr > 0.0) ? (job.host_sr / kModelSampleRate) : 1.0;
        auto resampled = decode_resampler_.process(finalized, ratio);
        output_queue_.enqueue(std::move(resampled));
    }

    // Bangs underrun_out on both the entering-underrun and the
    // recovering-from-underrun transitions, in place of the console log
    // this used to print -- much cleaner to patch against in Max than
    // parsing console text. Rate-limited to at most one bang per second
    // regardless of how many times the state actually flips within that
    // window: 32k/44k run close enough to the edge of real-time that
    // underrun/recovery can oscillate many times per second rather than
    // as one long dropout, and underrun_out's own fifo defer-to-scheduler
    // queue has no bound on how many bangs it will accumulate before the
    // next scheduler tick delivers them. Called from the audio thread
    // (under audio_mutex_, like the rest of operator()); std::chrono is
    // safe to use there, and underrun_out.send() itself never blocks —
    // it just pushes onto its own lock-free fifo (see the underrun_out
    // declaration's comment).
    void notify_underrun_transition() {
        auto now = std::chrono::steady_clock::now();
        if (now - last_underrun_event_ < std::chrono::milliseconds(1000))
            return;
        last_underrun_event_ = now;
        underrun_out.send(k_sym_bang);
    }

    // Every crash seen so far in the buffer modules traced back to a call
    // to error() -- post() has been reliable throughout. Route everything
    // through post() with an "ERROR:" prefix instead.
    void flush_output() {
        std::pair<bool,std::string> log_msg;
        while (log_queue_.try_dequeue(log_msg)) {
            if (log_msg.first) c74::max::post("%s", ("ERROR: " + log_msg.second).c_str());
            else c74::max::post("%s", log_msg.second.c_str());
        }
    }

    void start_output_timer() {
        output_timer_.delay(10);
    }

    void stop_output_timer() {
        output_timer_.stop();
    }

    // min-api's error()/post() are only safe to call from the main thread —
    // calling them directly here (this runs on worker_thread_) can throw
    // from inside min-api itself, and an exception escaping a std::thread's
    // entry point is an instant abort(). So log_queue_ carries the message
    // to flush_output(), which the output_timer_ only ever runs on the main
    // thread, and it does the actual error()/post() call from there.
    void load_model(const std::string& path) {
        try {
            session_.reset();
            auto* env = ONNXManager::instance().get_env();
            if (!env) {
                log_queue_.enqueue({true, "ncs.rt.snac44kh.decode~: ONNX Runtime not available"});
                return;
            }
            // Adaptive intra-op threads -- see
            // ncs.rt.snac44kh.encode_tilde.cpp's comment: this is the
            // OTHER compute-heavy Run() (context+new through the
            // decoder), same real-time budget pressure.
            session_options_.SetIntraOpNumThreads(adaptive_intra_op_threads());
            session_options_.SetGraphOptimizationLevel(
                GraphOptimizationLevel::ORT_ENABLE_EXTENDED);
            // Every ncs.*/ncs.rt.* module shares one process-wide
            // Ort::Env (ONNXManager, shared_external_helpers.h); the
            // default CPU memory arena + memory-pattern planner mutate
            // shared allocator bookkeeping under concurrent Run() calls
            // across sessions on different worker threads. Buffer mode's
            // rare one-shot-bang calls never hit this, but rt~'s
            // continuous Run()-every-block cadence caused a heap
            // corruption inside ONNX Runtime's own mem-pattern planner
            // (confirmed via crash report: abort() in malloc's free-list
            // checksum check, inside MemPatternPlanner::GenerateMemPattern(),
            // on a different rt module's worker thread mid-Run()).
            // Disabling both removes that shared/mutated code path; the
            // cost is moot given how small these tensors are.
            session_options_.DisableCpuMemArena();
            session_options_.DisableMemPattern();
            session_ = std::make_unique<Ort::Session>(*env, path.c_str(),
                                                       session_options_);
            ONNXManager::instance().release_env();

            auto input_type = session_->GetInputTypeInfo(0);
            input_name_ = session_->GetInputNameAllocated(0, allocator_).get();
            input_dims_ = input_type.GetTensorTypeAndShapeInfo().GetShape();

            auto output_type = session_->GetOutputTypeInfo(0);
            output_name_ = session_->GetOutputNameAllocated(0, allocator_).get();
            output_dims_ = output_type.GetTensorTypeAndShapeInfo().GetShape();

            model_loaded_ = true;
        } catch (const std::exception& ex) {
            log_queue_.enqueue({true, "ncs.rt.snac44kh.decode~: failed to load model (" + path + ") — "
                                        + std::string(ex.what()) + ". Models are expected at "
                                        + default_model_path_ + "."});
            model_loaded_ = false;
        }
    }

    std::vector<float> run_onnx(const std::vector<float>& input) {
        if (!session_ || !model_loaded_) return {};
        try {
            std::vector<int64_t> shape = input_dims_;
            if (!shape.empty() && shape[0] == -1) shape[0] = 1;
            if (!shape.empty() && shape.back() == -1) {
                // z_q is [B, 1024, T] -- the flattened input covers every
                // dim, so the dynamic trailing dim is input.size() divided
                // by the product of the static middle dims (1024), not
                // input.size() itself.
                int64_t known = 1;
                for (size_t i = 1; i + 1 < shape.size(); ++i) known *= shape[i];
                shape.back() = known > 0 ? static_cast<int64_t>(input.size()) / known
                                         : static_cast<int64_t>(input.size());
            }

            auto tensor = vector_to_tensor(input, shape, allocator_);
            const char* in_names[]  = {input_name_.c_str()};
            const char* out_names[] = {output_name_.c_str()};
            Ort::RunOptions opts;
            auto outputs = session_->Run(opts, in_names, &tensor, 1,
                                           out_names, 1);
            if (outputs.size() > 0)
                return tensor_to_vector(outputs[0]);
        } catch (const std::exception&) {}
        return {};
    }
};

MIN_EXTERNAL(NcsRtSnac44khDecode);
