// -----------------------------------------------------------------------------
// ncs.snac_24kh.encode  —  generated by Max External Template Generator
// -----------------------------------------------------------------------------

#ifdef _WIN32
#include <windows.h>
#endif

#include "c74_min.h"
#include "ext.h"
#include "../include/tsqueue.h"

#include "../include/shared_external_helpers.h"
#include "../include/onnx_helpers.h"
#include "../include/buffer_helpers.h"
#include <algorithm>
#include <atomic>
#include <chrono>
#include <cmath>
#include <memory>
#include <mutex>
#include <string>
#include <thread>
#include <utility>
#include <vector>

using namespace c74::min;

// SNAC 24kHz: hop_length=512, vq_strides=[4,2,1], attn_window_size=none.
// preprocess() in the reference model pads audio to a multiple of
// hop_length * lcm(vq_strides[0], attn_window_size or 1) = 512 * 4 = 2048.
static constexpr int64_t kHopLength   = 512;
static constexpr int64_t kPadMultiple = 2048;

// Buffer mode processes the whole signal in one ONNX forward pass and
// emits it as a single Max list message (768 floats per frame). A ~20s
// buffer (~722k atoms) was confirmed to crash Max itself: EXC_BAD_ACCESS
// inside Max's own outlet_cache/real_outlet_list (a raw memmove onto a
// corrupted/wrapped-around address), not something a try/catch here can
// guard against -- it's an overflow inside Max's C list-handling, not a
// C++ exception. Capping an order of magnitude lower for real safety
// margin; longer material needs chunking or the real-time streaming variant.
static constexpr size_t kMaxInputSamples = 50000; // ~2s @ 24kHz

class NcsSnac_24khEncode : public object<NcsSnac_24khEncode>
{
public:
    MIN_DESCRIPTION     {"Reads a named buffer~, runs the SNAC 24kHz encoder."};
    MIN_TAGS            {"snac, onnx, audio"};
    MIN_AUTHOR          {"Behzad Haki"};
    inlet<> control_in{ this, "(set/bang/load) buffer name, trigger, or model path" };
    outlet<> embeddings_out{ this, "(list) latent embeddings, channel-major flattened [768 x T]" };
    outlet<> length_out{ this, "(int) original buffer length in samples, before padding" };

    buffer_reference buffer_ref_{ this };

    // @buffername lets the input buffer~ be set as an object-box argument
    // (@buffername myBuf) or attribute message, alongside the 'set'
    // message buffer_reference already provides. An attribute's setter
    // runs immediately at construction with its default value ("" here)
    // -- guard against binding an empty-named buffer, an untested call
    // into Max's buffer subsystem that crashed on patch load.
    attribute<symbol> buffername{ this, "buffername", "", description{"Name of the buffer~ to read from."},
        setter{ MIN_FUNCTION {
            symbol name = (symbol)args[0];
            if (name != symbol(""))
                buffer_ref_.set(name);
            return {args};
        }}};

    // =====================================================================
    // CONSTRUCTOR / DESTRUCTOR
    // =====================================================================
    NcsSnac_24khEncode()
        : output_timer_{this, MIN_FUNCTION { flush_output(); output_timer_.delay(10); return {}; }}
    {
        start_worker();
        start_output_timer();
        // Auto-load the model shipped alongside this external -- resolves
        // to <package>/models/snac_onnx_exports/24khz/encode_audio_segment.onnx
        // relative to the deployed .mxo bundle. `load <path>` still works
        // afterwards to point at a different model.
        load_queue_.enqueue(BundleResourceLoader::get_resource_path(
            "models/snac_onnx_exports/24khz/encode_audio_segment.onnx"));
    }

    ~NcsSnac_24khEncode() {
        stop_worker();
        stop_output_timer();
    }

    // buffer~ access must happen on the main thread -- min-api's
    // buffer_lock wraps Max's buffer_edit_begin/buffer_edit_end, which are
    // not safe to call from an arbitrary spawned std::thread (only the
    // main thread or the audio thread, per every min-api/min-devkit
    // example). So the read happens here, synchronously, and only the
    // padded samples (pure data) cross over to the worker thread for the
    // actual (slow) ONNX inference.
    // This handler runs inside Max's own C dispatch loop -- an exception
    // escaping it does not unwind cleanly, it hits std::terminate() and
    // takes the whole host process down. read_mono() already catches
    // internally, but the resize/enqueue below is wrapped too, defensively.
    // Error reporting is routed through log_queue_ + flush_output() rather
    // than calling error() inline here: a bang can arrive very early
    // (e.g. from a loadbang, before the buffer is even set), and calling
    // error() synchronously at that point crashed Max's console/UI --
    // deferring it to the timer callback (the same path already used for
    // worker-thread errors) avoids that.
    message<> bang_msg{this, "bang", "Read the referenced buffer~ and run the encoder",
        MIN_FUNCTION {
            try {
                auto samples = ncs_buffer::read_mono(buffer_ref_);
                if (samples.empty()) {
                    log_queue_.enqueue({true, "ncs.snac_24kh.encode: buffer not found or empty"});
                    return {};
                }
                if (samples.size() > kMaxInputSamples) {
                    log_queue_.enqueue({true, "ncs.snac_24kh.encode: buffer is " + std::to_string(samples.size())
                          + " samples, over the " + std::to_string(kMaxInputSamples)
                          + "-sample (~2s) buffer-mode limit — split it into shorter chunks"});
                    return {};
                }
                int original_length = static_cast<int>(samples.size());
                int64_t padded_length = ((static_cast<int64_t>(samples.size()) + kPadMultiple - 1)
                                          / kPadMultiple) * kPadMultiple;
                samples.resize(static_cast<size_t>(padded_length), 0.0f);
                input_queue_.enqueue({std::move(samples), original_length});
            } catch (const std::exception& ex) {
                log_queue_.enqueue({true, "ncs.snac_24kh.encode: bang failed — " + std::string(ex.what())});
            }
            return {};
        }};

    message<> load{this, "load", "Load an ONNX model (.onnx)",
        MIN_FUNCTION {
            if (args.size() < 1) {
                log_queue_.enqueue({true, "ncs.snac_24kh.encode: load requires a file path"});
                return {};
            }
            load_queue_.enqueue((std::string)args[0]);
            return {};
        }};

// =============================================================================
// PRIVATE
// =============================================================================
private:
    std::thread worker_thread_;
    std::atomic<bool> worker_running_{false};
    std::atomic<bool> stop_{false};

    tsqueue<std::pair<std::vector<float>, int>> input_queue_;
    tsqueue<std::vector<float>> output_queue_;
    tsqueue<int> length_out_queue_;
    tsqueue<std::string> load_queue_;
    tsqueue<std::pair<bool,std::string>> log_queue_;

    timer<> output_timer_;

    bool model_loaded_{false};
    std::unique_ptr<Ort::Session> session_;
    Ort::SessionOptions session_options_;
    Ort::AllocatorWithDefaultOptions allocator_;
    std::string input_name_;
    std::string output_name_;
    std::vector<int64_t> input_dims_;
    std::vector<int64_t> output_dims_;

    void start_worker() {
        if (worker_running_.exchange(true)) return;
        stop_ = false;
        worker_thread_ = std::thread([this] { worker_loop(); });
    }

    void stop_worker() {
        stop_ = true;
        input_queue_.shutdown();
        load_queue_.shutdown();
        if (worker_thread_.joinable()) {
            if (worker_thread_.get_id() != std::this_thread::get_id())
                worker_thread_.join();
            else
                worker_thread_.detach();
        }
        worker_running_ = false;
    }

    void worker_loop() {
        while (!stop_) {
            std::string path;
            if (load_queue_.try_dequeue(path))
                load_model(path);
            std::pair<std::vector<float>, int> item;
            if (!input_queue_.wait_dequeue(item, 100))
                continue;
            std::pair<std::vector<float>, int> temp;
            while (input_queue_.try_dequeue(temp))
                item = std::move(temp);
            process(item.first, item.second);
        }
    }

    void process(const std::vector<float>& padded_samples, int original_length) {
        if (!model_loaded_) {
            log_queue_.enqueue({true, "ncs.snac_24kh.encode: no model loaded"});
            return;
        }
        auto z = run_onnx(padded_samples);
        if (z.empty()) {
            log_queue_.enqueue({true, "ncs.snac_24kh.encode: inference failed"});
            return;
        }
        output_queue_.enqueue(std::move(z));
        length_out_queue_.enqueue(original_length);
    }

    // Every crash seen so far traced back to a call to error() -- post()
    // has been reliable throughout. Route everything through post() with
    // an "ERROR:" prefix instead, to avoid whatever error() is doing
    // (likely highlighting the object in the patcher) that's unsafe here.
    void flush_output() {
        std::pair<bool,std::string> log_msg;
        while (log_queue_.try_dequeue(log_msg)) {
            if (log_msg.first) c74::max::post("%s", ("ERROR: " + log_msg.second).c_str());
            else c74::max::post("%s", log_msg.second.c_str());
        }
        // fire the length outlet before the embeddings outlet so that a
        // patch cord run in parallel to a downstream decode~'s length
        // inlet is guaranteed to have the value cached before the
        // embeddings arrive there (after the vq/embedcodes hop).
        int len;
        if (length_out_queue_.try_dequeue(len))
            length_out.send(len);
        std::vector<float> result;
        if (output_queue_.try_dequeue(result)) {
            atoms out_atoms(result.begin(), result.end());
            embeddings_out.send(out_atoms);
        }
    }

    void start_output_timer() {
        output_timer_.delay(10);
    }

    void stop_output_timer() {
        output_timer_.stop();
    }

    // min-api's error()/post() are only safe to call from the main thread —
    // calling them directly here (this runs on worker_thread_) can throw
    // from inside min-api itself, and an exception escaping a std::thread's
    // entry point is an instant abort(). So log_queue_ carries the message
    // to flush_output(), which the output_timer_ only ever runs on the main
    // thread, and it does the actual error()/post() call from there.
    void load_model(const std::string& path) {
        try {
            session_.reset();
            auto* env = ONNXManager::instance().get_env();
            if (!env) {
                log_queue_.enqueue({true, "ncs.snac_24kh.encode: ONNX Runtime not available"});
                return;
            }
            session_options_.SetIntraOpNumThreads(1);
            session_options_.SetGraphOptimizationLevel(
                GraphOptimizationLevel::ORT_ENABLE_EXTENDED);
            session_ = std::make_unique<Ort::Session>(*env, path.c_str(),
                                                       session_options_);
            ONNXManager::instance().release_env();

            auto input_type = session_->GetInputTypeInfo(0);
            input_name_ = session_->GetInputNameAllocated(0, allocator_).get();
            input_dims_ = input_type.GetTensorTypeAndShapeInfo().GetShape();

            auto output_type = session_->GetOutputTypeInfo(0);
            output_name_ = session_->GetOutputNameAllocated(0, allocator_).get();
            output_dims_ = output_type.GetTensorTypeAndShapeInfo().GetShape();

            model_loaded_ = true;
            log_queue_.enqueue({false, "ncs.snac_24kh.encode: loaded model (" + path + ")"});
        } catch (const std::exception& ex) {
            log_queue_.enqueue({true, "ncs.snac_24kh.encode: failed to load model — " + std::string(ex.what())});
            model_loaded_ = false;
        }
    }

    std::vector<float> run_onnx(const std::vector<float>& input) {
        if (!session_ || !model_loaded_) return {};
        try {
            std::vector<int64_t> shape = input_dims_;
            if (!shape.empty() && shape[0] == -1) shape[0] = 1;
            if (!shape.empty() && shape.back() == -1) {
                // audio is [B, 1, T] -- the dynamic trailing dim is
                // input.size() divided by the product of the static
                // middle dims (1 here, but computed generically).
                int64_t known = 1;
                for (size_t i = 1; i + 1 < shape.size(); ++i) known *= shape[i];
                shape.back() = known > 0 ? static_cast<int64_t>(input.size()) / known
                                         : static_cast<int64_t>(input.size());
            }

            auto tensor = vector_to_tensor(input, shape, allocator_);
            const char* in_names[]  = {input_name_.c_str()};
            const char* out_names[] = {output_name_.c_str()};
            Ort::RunOptions opts;
            auto outputs = session_->Run(opts, in_names, &tensor, 1,
                                           out_names, 1);
            if (outputs.size() > 0)
                return tensor_to_vector(outputs[0]);
        } catch (const std::exception&) {}
        return {};
    }
};

MIN_EXTERNAL(NcsSnac_24khEncode);
