// -----------------------------------------------------------------------------
// ncs.rt.snac_24kh.encode~  —  generated by Max External Template Generator
// -----------------------------------------------------------------------------

#ifdef _WIN32
#include <windows.h>
#endif

#include "c74_min.h"
#include "ext.h"
#include "../include/tsqueue.h"

#include "../include/shared_external_helpers.h"
#include "../include/onnx_helpers.h"
#include <algorithm>
#include <atomic>
#include <chrono>
#include <cmath>
#include <memory>
#include <mutex>
#include <string>
#include <thread>
#include <utility>
#include <vector>

using namespace c74::min;

class NcsRtSnac_24khEncode : public object<NcsRtSnac_24khEncode>
    , public sample_operator<1, 0>
{
public:
    MIN_DESCRIPTION     {""};
    MIN_TAGS            {""};
    MIN_AUTHOR          {"Behzad Haki"};
    inlet<> signal_in{ this, "(signal) audio input" };
    outlet<> result_out{ this, "(list) inference result" };

    // =====================================================================
    // CONSTRUCTOR / DESTRUCTOR
    // =====================================================================
    NcsRtSnac_24khEncode()
        : output_timer_{this, MIN_FUNCTION { flush_output(); output_timer_.delay(10); return {}; }}
    {
        start_worker();
        start_output_timer();
    }

    ~NcsRtSnac_24khEncode() {
        stop_worker();
        stop_output_timer();
    }

    sample operator()(sample in) {
        // Accumulate incoming samples into a block and ship it to the
        // worker thread the moment it's full — no extra buffering.
        input_accum_.push_back(static_cast<float>(in));
        if (input_accum_.size() >= kBlockSize) {
            input_queue_.enqueue(std::move(input_accum_));
            input_accum_.clear();
            input_accum_.reserve(kBlockSize);
        }
        return 0.0;
    }


    message<> load{this, "load", "Load an ONNX model (.onnx)",
        MIN_FUNCTION {
            if (args.size() < 1) {
                error("ncs.rt.snac_24kh.encode~: load requires a file path");
                return {};
            }
            load_queue_.enqueue((std::string)args[0]);
            return {};
        }};

    // =====================================================================
    // BANG
    // =====================================================================
    void bang() {}

// =============================================================================
// PRIVATE
// =============================================================================
private:
    std::thread worker_thread_;
    std::atomic<bool> worker_running_{false};
    std::atomic<bool> stop_{false};

    tsqueue<std::vector<float>> input_queue_;
    tsqueue<std::vector<float>> output_queue_;
    tsqueue<std::string> load_queue_;
    tsqueue<std::pair<bool,std::string>> log_queue_;

    // Audio-in accumulation block (sent to the worker as soon as it's full)
    static constexpr size_t kBlockSize = 512;
    std::vector<float> input_accum_;

    timer<> output_timer_;

    bool model_loaded_{false};
    std::unique_ptr<Ort::Session> session_;
    Ort::SessionOptions session_options_;
    Ort::AllocatorWithDefaultOptions allocator_;
    std::string input_name_;
    std::string output_name_;
    std::vector<int64_t> input_dims_;
    std::vector<int64_t> output_dims_;

    void start_worker() {
        if (worker_running_.exchange(true)) return;
        stop_ = false;
        worker_thread_ = std::thread([this] { worker_loop(); });
    }

    void stop_worker() {
        stop_ = true;
        input_queue_.shutdown();
        load_queue_.shutdown();
        if (worker_thread_.joinable()) {
            if (worker_thread_.get_id() != std::this_thread::get_id())
                worker_thread_.join();
            else
                worker_thread_.detach();
        }
        worker_running_ = false;
    }

    void worker_loop() {
        while (!stop_) {
            std::string path;
            if (load_queue_.try_dequeue(path))
                load_model(path);
            std::vector<float> input;
            if (!input_queue_.wait_dequeue(input, 100))
                continue;
            std::vector<float> temp;
            while (input_queue_.try_dequeue(temp))
                input = std::move(temp);
            process(input);
        }
    }

    void process(const std::vector<float>& msg) {
        if (model_loaded_) {
            auto result = run_onnx(msg);
            output_queue_.enqueue(std::move(result));
        }
    }

    void flush_output() {
        std::pair<bool,std::string> log_msg;
        while (log_queue_.try_dequeue(log_msg)) {
            if (log_msg.first) error(log_msg.second);
            else c74::max::post("%s", log_msg.second.c_str());
        }
        std::vector<float> result;
        if (output_queue_.try_dequeue(result)) {
            std::vector<float> temp;
            while (output_queue_.try_dequeue(temp))
                result = std::move(temp);
            atoms out_atoms(result.begin(), result.end());
            result_out.send(out_atoms);
        }
    }

    void start_output_timer() {
        output_timer_.delay(10);
    }

    void stop_output_timer() {
        output_timer_.stop();
    }

    // min-api's error()/post() are only safe to call from the main thread —
    // calling them directly here (this runs on worker_thread_) can throw
    // from inside min-api itself, and an exception escaping a std::thread's
    // entry point is an instant abort(). So log_queue_ carries the message
    // to flush_output(), which the output_timer_ only ever runs on the main
    // thread, and it does the actual error()/post() call from there.
    void load_model(const std::string& path) {
        try {
            session_.reset();
            auto* env = ONNXManager::instance().get_env();
            if (!env) {
                log_queue_.enqueue({true, "ncs.rt.snac_24kh.encode~: ONNX Runtime not available"});
                return;
            }
            session_options_.SetIntraOpNumThreads(1);
            session_options_.SetGraphOptimizationLevel(
                GraphOptimizationLevel::ORT_ENABLE_EXTENDED);
            session_ = std::make_unique<Ort::Session>(*env, path.c_str(),
                                                       session_options_);
            ONNXManager::instance().release_env();

            auto input_type = session_->GetInputTypeInfo(0);
            input_name_ = session_->GetInputNameAllocated(0, allocator_).get();
            input_dims_ = input_type.GetTensorTypeAndShapeInfo().GetShape();

            auto output_type = session_->GetOutputTypeInfo(0);
            output_name_ = session_->GetOutputNameAllocated(0, allocator_).get();
            output_dims_ = output_type.GetTensorTypeAndShapeInfo().GetShape();

            model_loaded_ = true;
            log_queue_.enqueue({false, "ncs.rt.snac_24kh.encode~: loaded model (" + path + ")"});
        } catch (const std::exception& ex) {
            log_queue_.enqueue({true, "ncs.rt.snac_24kh.encode~: failed to load model — " + std::string(ex.what())});
            model_loaded_ = false;
        }
    }

    std::vector<float> run_onnx(const std::vector<float>& input) {
        if (!session_ || !model_loaded_) return {};
        try {
            std::vector<int64_t> shape = input_dims_;
            if (!shape.empty() && shape[0] == -1) shape[0] = 1;
            if (!shape.empty() && shape.back() == -1)
                shape.back() = static_cast<int64_t>(input.size());

            auto tensor = vector_to_tensor(input, shape, allocator_);
            const char* in_names[]  = {input_name_.c_str()};
            const char* out_names[] = {output_name_.c_str()};
            Ort::RunOptions opts;
            auto outputs = session_->Run(opts, in_names, &tensor, 1,
                                           out_names, 1);
            if (outputs.size() > 0)
                return tensor_to_vector(outputs[0]);
        } catch (const std::exception&) {}
        return {};
    }
};

MIN_EXTERNAL(NcsRtSnac_24khEncode);
